unicorn-engine/unicorn

bindings/python/unicorn/unicorn.py

El Capitan does	not guaranteed that
(DY)LD_LIBRARY_PATH will exist, so force
one last check for the default install
directory that the install script uses.

Add OSX	10.11 dylib load fix

---

README.md

- A little correction in the license. It was "open source" rather than "free software". I know it's not very important for some people, but other people care about that.
- Linked COPYING file to the "GPL license" at the end of the README.

Small correction in README

---

qemu/target-i386/unicorn.c

this matches the segment management in qemu-user and is required to emulate the FS/GS register behavior

allow setting x86 segment base to host-sized value

---

.gitignore
Makefile

This fixes #205.
This change only affects *nix builds, and shouldn't affect `libunicorn.dll` on mingw, for example. However, it'd be nice if someone can build it to make sure. (It would be great if we had CI for this!)

create versioned library name and symlink unversioned name on *nix

---

COMPILE.TXT

trivial typo fix to installation path

COMPILE.TXT: fix trivial typo

---

bindings/python/README.TXT

clarify in which directory to build the core project and install the python bindings. when i went to install the python bindings, i was momentarily confused why the root Makefile didn't have an `install3` target.

python README.TXT: clarify working directories

---

tests/regress/hook_code_stop_emu.py

tests (and currently reports a failure) on py2 & py3
```
[willi@hostname regress]$ python3 hook_code_stop_emu.py 
pc: 0x1000
F
======================================================================
FAIL: test_hook_code_stop_emu (__main__.HookCodeStopEmuTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "hook_code_stop_emu.py", line 76, in test_hook_code_stop_emu
"Emulator failed to stop after one instruction")
AssertionError: 4103 != 4105 : Emulator failed to stop after one instruction
----------------------------------------------------------------------
Ran 1 test in 0.002s
FAILED (failures=1)
```

add hook_code_stop_emu.py test for issue #232

---

bindings/python/unicorn/__init__.py
bindings/python/unicorn/unicorn.py

closes #235.
works on test scripts on my system. please double check bindings continue to work for you under py2.

python bindings: use relative paths for imports to support py3

---

tests/regress/segfault_on_stop.py
uc.c

Fix for the following segfault:
```python
unicorn.Uc(unicorn.UC_ARCH_X86, unicorn.UC_MODE_64).emu_stop()
...
python[23549]: segfault at ac ip 00007fc5395fe682 sp 00007fffb7093b90 error 6 in libunicorn.so.0[7fc5394cc000+915000]
```

Fix segfault on emu_stop()

---

tests/regress/init.py

Machine:
> uname -a
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
> cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
Output:
[+] Emulating IP: 10004cd SP: 80004cd - Counter: 4ce
[+] Emulating IP: 10004ce SP: 80004ce - Counter: 4cf
[+] Emulating IP: 10004cf SP: 80004cf - Counter: 4d0
[+] Emulating IP: 10004d0 SP: 80004d0 - Counter: 4d1
[+] Emulating IP: 10004d1 SP: 80004d1 - Counter: 4d2
Aborted (core dumped)
Backtrace:                
12:09:41 emdel -> gdb -q /usr/bin/python core
Reading symbols from /usr/bin/python...(no debugging symbols found)...done.
warning: core file may not match specified executable file.
[New LWP 56366]
[New LWP 57600] …

SIGABRT issue

---

tests/regress/00opcode_uc_crash.c
tests/regress/Makefile

The opcode 0x00 translates as `add byte ptr ds:[eax],al`, which leads to
a segfault in Unicorn.
Using a debugger, I believe the crash is located in
`qemu/translate-all.c` in function `page_flush_tb_1`, more specifically
this code `pd[i].first_tb = NULL;`

X86 zero-byte opcode causes Unicorn to crash.

---

include/unicorn/m68k.h

Fix this error:
```
In file included from ./unicorn_capstone.c:6:
In file included from /usr/include/capstone/capstone.h:242:
/usr/include/capstone/m68k.h:21:14: error: redefinition of 'm68k_reg'
typedef enum m68k_reg {
^
/usr/include/unicorn/m68k.h:19:14: note: previous definition is here
typedef enum m68k_reg {
^
In file included from ./unicorn_capstone.c:6:
In file included from /usr/include/capstone/capstone.h:242:
/usr/include/capstone/m68k.h:77:3: error: typedef redefinition with different
types ('enum m68k_reg' (aka 'm68k_reg') vs 'enum m68k_reg')
} m68k_reg;
^
/usr/include/unicorn/m68k.h:44:3: note: previous definition is here
} m68k_reg;
^
2 errors generated.
```

fix compilation with capstone next

---

tests/regress/Makefile
tests/regress/eflags_noset.c

When attempting to set all flags except trap flag, the EFLAGS value
should be 0x00244ED7, I've tested this on Windows and here
https://ideone.com/WQAvk1 which is presumably Linux.
Unicorn however has the value 0x00000ED7, bits 11-21 are not set. Bit 21
is the ID bit indicating whether or not CPUID is available.

Attempting to set some bits in the Unicorn EFLAGS doesn't work.

---

tests/regress/run_across_bb.py

Expected behavior: the test passes.
Observed behavior: test fails:
```
[willi@hostname regress]$ python2 run_across_bb.py 
pc: 0x1000
>>> Tracing instruction at 0x1000, instruction size = 5
>>> Tracing instruction at 0x1005, instruction size = 1
>>> Tracing instruction at 0x1006, instruction size = 1
>>> Tracing instruction at 0x1007, instruction size = 5
pc: 0x100c
>>> Tracing instruction at 0x100c, instruction size = 1
!!! about to bail due to bad fetch... here's the data at PC:
b800000000404000
F
======================================================================
FAIL: test_run_across_bb (__main__.RunAcrossBBTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "run_across_bb.py", line 133, in test_run_across_bb …
```

Add test for emulation within and across BBs

---

tests/regress/run_across_bb.py

demonstrates that calling `emu_start` from a BB start to another BB end works fine. its starting/stopping within a block that seems broken.
associated issue #263

add test case to run_across_bb.py

---

.gitignore
tests/regress/Makefile
tests/regress/mem_nofree.c

While uc_mem_unmap does unmap memory regions from Unicorn, it does not
free the memory. It accumulates over time when reusing a single Unicorn instance.

Unmapped memory is not freed.

---

tests/regress/mips_branch_delay.py

The disasm function was not printing the instruction mnemonic it was only printing instruction operands. This was changed to now print the mnemonic as well.

Added mnemonic printing to disasm function.

---

qemu/memory.c
uc.c

It appears the problem is that we are not calling the memory region
destructor. After modifying memory_unmap to include the destructor call
for the memory region, the memory is freed.
Furthermore in uc_close we must explicitly free any blocks that were not
unmapped by the user to prevent leaks.
This should fix issue 305.

Fix uc_mem_unmap memory leak and in uc_close.

---

qemu/memory.c
uc.c

Although I am not sure why mr->enabled needs to be set to false when we are uninitializing everything.

Fix segfault introduced in my previous commits.

---

bindings/msvc/samples/main.c
bindings/msvc/unicorn_dynload.c
bindings/msvc/unicorn_dynload.h
samples/mem_apis.c
samples/sample_arm.c
samples/sample_arm64.c
samples/sample_m68k.c
samples/sample_mips.c
samples/sample_sparc.c
samples/sample_x86.c
samples/shellcode.c

Some fixes for the including of the unicorn_dynload.h file after moving it.
(Yes I know I said no changes were required. I was wrong :))

Fixed includes for moved unicorn_dynload.h file

---

.gitignore
tests/regress/Makefile
tests/regress/mips_delay_slot_code_hook.c
tests/regress/rw_hookstack.c

Changed the tests/regress/Makefile to support windows lib file.
Changed the tests/regress/Makefile to have correct include path.
Added *.exe to gitignore so as to not include test exe files once built.
Fixed unicorn_dynload include for tests/regress/mips_delay_slot_code_hook.c

Added support for building tests from MinGW.

---

.gitignore
bindings/msvc/unicorn_dynload.c
tests/regress/Makefile
tests/regress/mips_delay_slot_code_hook.c
tests/regress/rw_hookstack.c

Fixed the unicorn_dynload.c version of uc_hook_add() to handle UC_HOOK_MEM_*_PROT and UC_HOOK_MEM_*_UNMAPPED.

Fixed the unicorn_dynload.c version of uc_hook_add() to handle UC_HOOK_MEM_*_PROT and UC_HOOK_MEM_*_UNMAPPED.

---

.gitignore
tests/regress/Makefile
tests/regress/mips_delay_slot_code_hook.c
tests/regress/threaded_emu_start.c

Currently "uc->qemu_global_mutex" is locked by uc_open() and unlocked
by uc_emu_start(). This is a problem because the mutex implementation
must be locked and unlocked by the same thread. This means that uc_open()
and uc_emu_start() must be executed in the same thread. This is an unnecessary
limitation since it is beneficial to be able to run the emulator in its own
thread without having to also do the initial setup for the emulator in the
same thread.
A quick fix for this would be to change the mutex lock to be a semaphore lock,
thereby allowing lock/unlock by different threads. A potential downside is
that sempahores are slower than mutexes, however from what I could see
this probably isn't an issue as "uc->qemu_global_mutex" doesn't appear to
be used when the emulator is running, just …

Added test for uc_open() and uc_emu_start() being called by different threads.

---

qemu/target-mips/translate.c

This fixes issue #290.
This reverts code changes that were added to fix issue #133, but that I believe to be incorrect.
Tests "mips_branch_delay.py" and "mips_delay_slot_code_hook.c" should now operate correctly.

Fix codehook for MIPS instructions in delay slot

---

.gitignore
tests/regress/Makefile
tests/regress/emu_stop_in_hook_overrun.c

Added test for uc_emu_stop() in code hook not always stopping the emu at the current instruction.
In the added code it should stop when executing the instruction at the address 0x100008 but you can see it goes on to execute the instrucion at 0x10000C before then stopping with a PC value being 0x10000C.

Emu stop in hook overrun

---

.gitignore
tests/regress/Makefile
tests/regress/mips_branch_likely_issue.c

Test for MIPS branch likely instructions only executing their delay slot instruction when the branch is taken.
Currently it seems to always execute the delay slot instruction like a normal non-"likely" style branch.

Added test for MIPS branch likely instructions.

---

.gitignore
tests/regress/Makefile
tests/regress/hook_extrainvoke.c

As I described before, the issue is caused by the particular way some instructions are jitted. The translation block is exited to store the data via the `helper_le_stl_mmu` helper and subsequently re-entered, in this test's case, it's re-entered to check if ECX > 0, invoking the hook one additional time.
This means that counting instructions can be incorrect with some instructions.
Currently, I've added the `rep stosd dword ptr es:[edi], eax` instruction, but likely all instructions prefixed with REP and/or just STOS are going to cause this, and any other instructions which need to exit the TB and re-enter it.

Add test for pre-instruction hook being invoked more times.

---

.gitignore
qemu/target-i386/helper.h
qemu/target-i386/seg_helper.c
qemu/target-i386/translate.c
qemu/target-i386/unicorn.c
tests/regress/Makefile
tests/regress/sysenter_hook_x86.c

helper_sysenter in qemu/target-i386/seg_helper.c didn't check properly if a call interrupt callback was registred.
It has been fixed by copying the helper_syscall behavior.

(Fix #341) SYSENTER instruction is not properly hooked with uc_hook_add in x86 emulation

---

tests/regress/mips_kernel_mmu.py

Created a regression test as requested in Issue #343. This test passes when the base address is less than KSEG0 (0x80000000) and currently fails when greater than or equal to KSEG0.

Regression test for MIPS kernel mode execution

---

tests/unit/Makefile
tests/unit/test_mem_map.c

Crashes if a page is unmapped after another page was mapped twice. Its unclear if mapping twice should fail or unmap should succeed.

added test for unmap of doubly mapped region

---

tests/regress/mem_nofree.c
tests/regress/mem_unmap.c

My mem_nofree test fails on the latest code as apparently my address and
sizes overlap each other.
The mem_unmap test failed as the invalid memory hook case was incorrect.
Additionally, if mem_map fails for some reason, the new allocated memory region is not stashed, and this creates a problem with my memory leak fixes.

Add some fixes to mem_unmap and mem_nofree tests.

---

.gitignore
COMPILE.TXT
Makefile
qemu/configure
qemu/tcg/i386/tcg-target.c
qemu/tcg/i386/tcg-target.h
qemu/util/oslib-posix.c
samples/Makefile

Unicorn can be built for Cygwin.
$ apt-cyg install make gcc-core pkg-config libpcre-devel zlib-devel libglib2.0-devel
$ ./make.sh install
--
Cygwin64
$ uname -srvmo
CYGWIN_NT-6.1 2.3.1(0.291/5/3) 2015-11-14 12:44 x86_64 Cygwin
$ gcc -dumpversion; gcc -dumpmachine
4.9.3
x86_64-pc-cygwin
--
Cygwin32
$ uname -srvmo
CYGWIN_NT-6.1-WOW 2.3.1(0.291/5/3) 2015-11-14 12:42 i686 Cygwin
$ gcc -dumpversion; gcc -dumpmachine
4.9.3
i686-pc-cygwin

Build for Cygwin

---

tests/regress/emu_clear_errors.py

Test case demonstrating issue #351.
The assembly code is a random fragment I found that exhibited the behavior in my project. Not sure why this sequence triggers it. Haven't thoroughly tested other fragments.
Here's the output I get:
```
hostname tests/regress ‹test/issue-351*› » python2 emu_clear_errors.py                                            1 ↵
mem unmapped: pc: 1000 access: 13 address: 28 length: 4 value: 0
pc: 0x1000
E
======================================================================
ERROR: test_hook_code_stop_emu (__main__.HookCodeStopEmuTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "emu_clear_errors.py", line 73, in test_hook_code_stop_emu
mu.emu_start(0x1004, 0x100F)
File …
```

add test case demonstrating issue 351

---

tests/regress/emu_clear_errors.c

as requested by @farmdve 
here's the output I get:
```
hostname tests/regress ‹test/issue-351*› » make all && ./emu_clear_errors
cc -I../../include emu_clear_errors.c ../../libunicorn.a -lglib-2.0 -lpthread -lm -o emu_clear_errors
ok 1 - uc_open
ok 2 - uc_mem_map: code
ok 3 - uc_mem_write: code
ok 4 - uc_reg_write: eip
ok 5 - uc_mem_map: stack
ok 6 - uc_mem_write: stack
ok 7 - uc_reg_write: esp
ok 8 - uc_reg_write: ebp
ok 9 - uc_hook_add
mem unmapped: 0x1000 type: 13 address: 0x28 length: 4 value: 0
ok 10 - uc_emu_start
ok 11 - uc_reg_write: eip
not ok 12 - Invalid memory read (UC_ERR_READ_UNMAPPED)
```

add test case in C demonstrating issue 351 in C

---

qemu/cpu-exec.c
uc.c

Should remove the INVALID memory error when re-using an instance. Should fix issue #351 and a fix for issue #369

Reset env->invalid_error before executing a translation block.

---

bindings/python/sample_network_auditing.py

- Added detect for Python 2/3 so the correct iteritems()/iter() is called, but without needing to install six
- Switch to 'in' which works in 2/3 instead of legacy '.has_key()'
- Renamed 'id' variable use (which is a built-in) to my_id.
- Small formatting changes to make it more PEP compliant.

Fix sample_network_auditing.py so it works with Python3

---

tests/regress/jumping.py

This testcase should set ZF and make RDX contain 'babe'.
For some reason, the emulator ignores my modifications.
We have the same behavior if we set the global variable zf to 0.
By playing with this global variable we should be able to jump in 
the two different branches. 
Surprisingly, the eflags register is always consistent with the emulation 
and thus RDX at the end always contains 'c0ca'
I'm not familiar with Qemu code, but I noticed the difference between 
env->eflags and env->eflags0.
I hope I'm not missing something trivial, and that my code makes sense :)
Any hint is really appreciated.

Testcase to set ZF and modify eflags in x86/x86_64

---

tests/unit/Makefile
tests/unit/test_x86_soft_paging.c

Test case for x86 paging using virtual addresses mapped by Unicorn, as well as unmapped.
Attempting to read/write from virtual address ranges unmapped by Unicorn wrongly causes protection faults, even when the virtual address points to read/write regions of Unicorn memory.
p.s. sorry for double pull

test case: x86 guest paging

---

qemu/target-i386/translate.c

If the value of the eflags register is changed inside the uc_tracecode helper, the previously computed value from helpers is used nevertheless, and the change is not taken into account. This patch forces a reload of the condition temporary from the eflags register value after each helper call.

Fixed restoring of eflags after helper call

---

include/uc_priv.h
qemu/target-arm/unicorn_aarch64.c
qemu/target-arm/unicorn_arm.c
qemu/target-i386/unicorn.c
qemu/target-m68k/unicorn.c
qemu/target-mips/unicorn.c
qemu/target-sparc/unicorn.c
qemu/target-sparc/unicorn64.c

`WRITE_BYTE_H()` macros in `qemu/target-*/unicorn*.c` are wrong, so `uc_reg_write()` doesn't work correctly for `UC_X86_REG_xH`.
```
$ ipython
In [1]: from unicorn import *
In [2]: from unicorn.x86_const import *
In [3]: mu = Uc(UC_ARCH_X86, UC_MODE_32)
In [4]: mu.reg_write(UC_X86_REG_EAX, 0x00000000)
In [5]: mu.reg_write(UC_X86_REG_AH, 0x12)
In [6]: '%08X' % mu.reg_read(UC_X86_REG_EAX)
Out[6]: '00000012' # expect '00001200'
In [7]: mu.reg_write(UC_X86_REG_EAX, 0xFFFFFFFF)
In [8]: mu.reg_write(UC_X86_REG_AH, 0x12)
In [9]: '%08X' % mu.reg_read(UC_X86_REG_EAX)
Out[9]: 'FFFF00FF' # expect 'FFFF12FF'
```

fix WRITE_BYTE_H() macro

---

include/unicorn/unicorn.h

Fix a typo in uc_hook_add documentation.

Fix a typo in uc_hook_add documentation.

---

bindings/python/unicorn/unicorn.py

uc_x86_mmr: Using of an attribute limits, but in Structure is named limit.

Bugfix: uc_x86_mmr has no attribute limits

---

qemu/translate-all.c

should fix #487
The size shrink is just for the default size. It will grow automatically.
The code gen buffer is stored in `uc->tcg_ctx` already.

static -> dynamic code buffer, and shrink 32M->8M

---

include/unicorn/x86.h

include/unicorn/x86.h referenced types defined in stdint.h (e.g. uint16_t, etc.), but didn't actually include stdint.h

Added stdint include to x86.h

---

tests/regress/x86_64_conditional_jump.py

This issue breaks emulation of conditional instructions on amd64.

Add test showing failure to track targets properly when single-stepping.

---

qemu/target-i386/translate.c

this outright breaks conditionals and needs to be done in a different way

remove call to restore_eflags (#496)

---

bindings/go/unicorn/uc.c
bindings/go/unicorn/uc.h
bindings/go/unicorn/unicorn.go
include/uc_priv.h
include/unicorn/unicorn.h
qemu/target-arm/unicorn.h
qemu/target-arm/unicorn_aarch64.c
qemu/target-arm/unicorn_arm.c
qemu/target-i386/unicorn.c
qemu/target-i386/unicorn.h
qemu/target-m68k/unicorn.c
qemu/target-m68k/unicorn.h
qemu/target-mips/unicorn.c
qemu/target-mips/unicorn.h
qemu/target-sparc/unicorn.c
qemu/target-sparc/unicorn.h
qemu/target-sparc/unicorn64.c
samples/Makefile
samples/sample_batch_reg.c
uc.c

add reg_read_batch and reg_write_batch API
this improves Usercorn's overall execution speed when doing a register trace by over 2x
related to #8
one of the reasons I want selective register access instead of all-at-once, is the syscall/function call ABI only requires a small subset of registers

add batched reg access

---

bindings/haskell/src/Unicorn/CPU/Arm.chs
bindings/haskell/src/Unicorn/CPU/Arm64.chs
bindings/haskell/src/Unicorn/CPU/M68k.chs
bindings/haskell/src/Unicorn/CPU/Mips.chs
bindings/haskell/src/Unicorn/CPU/Sparc.chs
bindings/haskell/src/Unicorn/CPU/X86.chs
bindings/haskell/src/Unicorn/Internal/Core.chs
bindings/haskell/src/Unicorn/Internal/Hook.chs
bindings/haskell/src/Unicorn/Internal/Unicorn.chs
bindings/haskell/src/Unicorn/Internal/Util.hs

`Enum`s now derive `Bounded` and I've made use of `Applicative` in the Utils module.

Small improvements to align with hapstone (Haskell bindings for Capstone)

---

.gitignore
tests/regress/001-bad_condition_code_0xe.c
tests/regress/002-qemu__fatal__unimplemented_control_register_write_0xffb___0x0.c
tests/regress/003-qemu__fatal__wdebug_not_implemented.c
tests/regress/004-segmentation_fault_1.c
tests/regress/005-qemu__fatal__illegal_instruction__0000___00000404.c
tests/regress/006-qemu__fatal__illegal_instruction__0421___00040026.c
tests/regress/Makefile

```
$ ./001-bad_condition_code_0xe # ARM
uc_emu_start(…)
Bad condition code 0xe
Aborted
$ ./002-qemu__fatal__unimplemented_control_register_write_0xffb___0x0 # M68K
uc_emu_start(…)
hook_code(…) called
qemu: fatal: Unimplemented control register write 0xffb = 0x0
Aborted
$ ./003-qemu__fatal__wdebug_not_implemented # M68K
uc_emu_start(…)
qemu: fatal: WDEBUG not implemented
Aborted
$ ./004-segmentation_fault_1 # ARM
uc_emu_start(…)
hook_code(…) called
Segmentation fault
$ ./005-qemu__fatal__illegal_instruction__0000___00000404 # M68K
uc_emu_start(…)
qemu: fatal: Illegal instruction: 0000 @ 00000404
Aborted
$ ./006-qemu__fatal__illegal_instruction__0421___00040026 # M68K
uc_emu_start(…)
hook_code(…) called
qemu: fatal: Illegal instruction: 0421 @ 00040026
Aborted
```

Add six crash cases (2 * ARM + 4 * M68K)

---

uc.c

This was previously released at uc_close ../uc.c:286
if (uc->release)
uc->release(uc->tcg_ctx);
Which effectively does:
object_unref(uc, OBJECT(uc->root));
Fixes #528

Remove double-free

---

qemu/cpus.c
qemu/vl.c
uc.c

There's no change to samples_all.sh output, and all regression tests looked to pass the same.
note: I'm pretty sure this makes some dead code, but I wanted the least intrusive patch possible

execute cpus in same thread as uc_emu_start()

---

Makefile
make.sh
samples/Makefile
tests/unit/Makefile

Note that using this with Python bindings (or, e.g. in GDB) will require adding `start_deactivated=1` to `ASAN_OPTIONS`.

Add ASAN build target with UNICORN_ASAN or via './make.sh asan'

---

bindings/msvc/unicorn.def
bindings/msvc/unicorn_dynload.c
include/unicorn/unicorn.h

Added MSVC bindings for uc_reg_write_batch() and uc_reg_read_batch() and fixed UC_HOOK_INSN hooking.
Also fixed the use of stdbool.h in MSVC since it is not included in MSVC.
(This fixes #541)

Add new bindings and fixed UC_HOOK_INSN hooking.

---

bindings/go/unicorn/unicorn.go

Fixed broken type in go bindings

fixed go bindings typo

---

docs/COMPILE-WINDOWS.md

On the default Markdown viewer on GitHub, some instructions for compiling aren't displayed correctly : 
https://github.com/unicorn-engine/unicorn/blob/4b3bbe4759fe0f4764aefef6a8354897076504f0/docs/COMPILE-WINDOWS.md

Update COMPILE-WINDOWS.md - Improve lisibility.

---

bindings/python/unicorn/unicorn.py

In order to make exceptions display well with the Python binding on Python 3.x, return exception message as unicode/str rather than str/bytes.

Python 3 compatibility: raise unicode exception messages

---

qemu/target-arm/unicorn_arm.c

I tested this with code compiled using a cross-compiler from the Android NDK and seems to work fine. I don't see why it would fail, but it might be worth running more ARM tests on it before merging.
See issue #391

Set thumb mode based on PC value in ARM. Mask off last bit of PC.

---

qemu/fpu/softfloat.c
qemu/include/fpu/softfloat.h

This is the fixed version of #609 that got accepted upstream.

Port patch from upstream to check for invalid long double encodings

---

tests/unit/test_hang.c
tests/unit/test_x86_rip_bug.c

Cleaned up the unit test for Issue #534, corrected the expected address for x86_64, added workaround to show proper of EIP/RIP.
Also contains a format string fix for tests/unit/test_hang.c

Unit Test for Issue #534 [Bug Fixes]

---

qemu/target-i386/cpu.h
tests/regress/x86_eflags.py

This is a patch to the x86 eflags computation. I don't know what it does, exactly, since someone else on the angr team wrote this and I don't understand the diff, but it makes the unicorn eflags match the libVEX eflags in tests we run to ensure accuracy.

eflags patch

---

bindings/haskell/unicorn.cabal

Haskell bindings do not build on GHC 8 due to too strict transformers constraint. This relaxes the constraint to fix the build.

Relax transformers constraint for haskell bindings for GHC 8

---

.gitignore
bindings/python/MANIFEST.in
bindings/python/Makefile
bindings/python/README.TXT
bindings/python/setup.py
bindings/python/unicorn/unicorn.py

- Build the shared library on python build/install
- Package the shared library and static library with the python library
- Package the headers with the python library, this allows the python distribution to be used as a canonical distribution if your project that depends on unicorn requires both the python bindings and links directly against the C library (this is the case for angr)
- Generally, clean up the python setup process
- Drastically simplify the python shared library import process
This is a *lot* of invasive changes to the build process, but what I see is that they just make it _work_ instead of having to have an `install_unicorn.sh` in the root of all of our projects that depend on unicorn. This was the case for a while in our internal repos...
If you like these, I have a …

Basically, make python builds work as expected

---

bindings/python/setup.py

before this patch:
```sh
$ sudo make install3
rm -rf src/ dist/
rm -rf prebuilt/win64/unicorn.dll
rm -rf prebuilt/win32/unicorn.dll
if test -n ""; then \
python3 setup.py install --root=""; \
else \
python3 setup.py install; \
fi
File "setup.py", line 165
print "Proper 'develop' support unavailable."
^
SyntaxError: Missing parentheses in call to 'print'
make: *** [install3] Error 1
```

bindings/python: fix install3

---

tests/regress/map_write.c

Fix potential leak, wrong text in log, and restyle
to a cleaner exit path

Fix leak and style in map_write.c

---

samples/sample_x86_32_gdt_and_seg_regs.c

This PR is to fix the following error that occurred while compiling unicorn-engine using MinGW32

changed '%02hhx' to '%02x' in sample_x86_32_gdt_and_seg_regs.c

---

bindings/python/setup.cfg
bindings/python/setup.py
bindings/python/unicorn/unicorn.py

I was successfully able to build and install working wheels for both mingw64 and mingw32.
Note that there's actually a bug in the msys distribution of python preventing bdist_wheel from working correctly. I submitted a patch to address this. https://github.com/Alexpux/MINGW-packages/pull/1899
Should address #671

Fixes to make python distribution for windows work

---

qemu/include/glib_compat.h

Added define for g_free so that integration w/ future versions of qemu won't require global search and replace of g_free to free

add g_free to make future integration easier

---

uc.c

this will be slightly slower (`UC_HOOK_MAX * len(hooks)` instead of `num_types * len(hooks)`) for removing hooks because we can't safely dereference a hook struct to get its types.
this could be fixed by aligning the hook's pointer and storing the hook types as a mask in the pointer value.

fix possible segfault in hook del (#691)

---

include/uc_priv.h
qemu/hw/arm/tosa.c

Support for Cortex-M ARM CPU already exists in Qemu. This patch just
exposes a "cortex-m3" CPU.
Example:
`uc_open(UC_ARCH_ARM, UC_MODE_THUMB | UC_MODE_MCLASS, &uc);`
Signed-off-by: Lucian Cojocar <lucian@cojocar.com>

Support for MCLASS ARM cpu (Cortex-M3)

---

windows_export.bat

Apparently batch scripts return with the return code of their last statement. Who knew.
See comment added in windows_export.bat

Make the call out to visual studio extremely resilient

---

bindings/python/setup.py

Copy prebuilt static library if available. Disallow uploads from builds that fail to provide the static library.
These are untested, they're just from me scrutinizing the code that's gonna get run as soon as my backup finishes.

Static library copying nitpicks

---

bindings/python/unicorn/unicorn.py
tests/regress/leaked_refs.py

Added a test case, requires `objgraph` module.

Fixed circular refs preventing Uc instances from being GC'd

---

qemu/util/qemu-thread-win32.c
uc.c

Fixed double free in win32 threads and changed free() to g_free().

Fixed double free in win32 threads and changed free() to g_free().

---

make.sh

Moved $UNAME variable initialization a few lines higher -- before it is used.

Fixed build script for *BSD

---

include/unicorn/platform.h
msvc/unicorn/unicorn/unicorn.vcxproj
msvc/unicorn/unicorn_static/unicorn_static.vcxproj
qemu/include/qemu/atomic.h
uc.c

Use waitable timer to implement usleep() on Windows and get rid of usage of socket library.

MSVC port (vardyh)

---

Makefile

Providing a default level of parallelism is perfectly fine, but it should also be possible to set higher or lower levels of parallelism easily. This is particularly beneficial for people packaging the software for Linux distributions.

Makefile: Allow for overriding job threads for making 'qemu' dir

---

bindings/python/unicorn/unicorn.py
qemu/target-arm/unicorn_aarch64.c

Fixing #773, including Python bindings.
Test:
```
In [1]: uc.reg_write(UC_ARM64_REG_Q0, 0x00112233445566778899aabbccddeeff)
In [2]: hex(uc.reg_read(UC_ARM64_REG_Q0))
Out[2]: '0x112233445566778899aabbccddeeffL'
In [3]: hex(uc.reg_read(UC_ARM64_REG_D0))
Out[3]: '0x8899aabbccddeeffL'
In [4]: hex(uc.reg_read(UC_ARM64_REG_S0))
Out[4]: '0xccddeeffL'
In [5]: hex(uc.reg_read(UC_ARM64_REG_H0))
Out[5]: '0xeeffL'
In [6]: hex(uc.reg_read(UC_ARM64_REG_B0))
Out[6]: '0xffL'
```
Also aliased `UC_ARM64_REG_V0` to `UC_ARM64_REG_Q0` since they are the same.

uc_reg_read & uc_reg_write now support ARM64 Neon registers

---

qemu/target-mips/unicorn.c

In Unicorn's interface to qemu/target-mips, reg_read and reg_write were only operating on the lower 32-bits of a 64-bit register. This change allows reading/writing the full register.

fix register widths for MIPS64 reg_read/write

---

uc.c

A memory region is allocated inside split_region() that was only freed in error case but not on success case, leading to huge memory leak if the region size was significant.

Fix huge memory leak on uc_mem_protect()

---

qemu/target-arm/unicorn_aarch64.c

unicorn_aarch64: Expose UC_ARM64_REG_NZCV register.

---

bindings/python/unicorn/unicorn.py

Very silly issue: I am using the python bindings, and for various reasons I don't have a PATH set in my environment. Right now I can't `import unicorn` because of that. That is stupid, this makes it better.

handle not having a path in python bindings

---

include/unicorn/unicorn.h

Updated the comment on UC_MEM_*_UNMAPPED to clarify what happens if "true" is returned

Update comments on UC_MEM_*_UNMAPPED

---

qemu/target-arm/cpu-qom.h
qemu/target-i386/cpu-qom.h
qemu/target-m68k/cpu-qom.h
qemu/target-mips/cpu-qom.h
qemu/target-sparc/cpu-qom.h

I don't think these have any value in Unicorn, as there's no public QOM API and we already know the object types at call sites. This increases batch register read throughput in the Go bindings by 8-12% based on a benchmark I wrote, and single register read by a few percent (Go has a large C function call overhead, which I think is dominating Unicorn's internal overhead for single register access).
```
$ go run bench.go # with the patch
running: x86_64
single reg: 1000000 in 437.443535ms  ( 2286009.32/s)
batch reg: 1000000 in 693.68116ms   (14415844.88/s)
single reg: 1000000 in 431.988547ms  ( 2314876.19/s)
batch reg: 1000000 in 688.839308ms  (14517173.87/s)
single reg: 1000000 in 432.21778ms   ( 2313648.46/s)
batch reg: 1000000 in 692.371699ms  (14443109.12/s)
single reg: 1000000 in …
```

remove slow cpu QOM casts

---

bindings/go/unicorn/reg_batch.go
bindings/go/unicorn/unicorn.go

This adds a second technique for batch reading regs in Go that's about 50% faster:
```
running: x86_64
single reg: 1000000 in 430.385148ms  ( 2323500.25/s)
single reg: 1000000 in 426.116067ms  ( 2346778.44/s)
single reg: 1000000 in 420.033392ms  ( 2380763.10/s)
single reg: 1000000 in 421.195042ms  ( 2374196.99/s)
single reg: 1000000 in 409.085793ms  ( 2444475.02/s)
batch: 1000000 in 66.105382ms   (15127361.34/s)
batch: 1000000 in 69.302988ms   (14429392.28/s)
batch: 1000000 in 69.14085ms    (14463229.77/s)
batch: 1000000 in 74.227314ms   (13472129.68/s)
batch: 1000000 in 68.082625ms   (14688035.31/s)
RegBatch: 1000000 in 40.463085ms   (24713884.27/s)
RegBatch: 1000000 in 42.801571ms   (23363628.41/s)
RegBatch: 1000000 in 43.444415ms   (23017918.41/s)
RegBatch: 1000000 in 44.891513ms …
```

go: add faster RegBatch type

---

bindings/go/unicorn/hook.go
bindings/go/unicorn/unicorn.go
bindings/go/unicorn/x86_test.go

Before: BenchmarkX86Hook-4    2000000    905 ns/op
After:  BenchmarkX86Hook-4    2000000    683 ns/op

Go: improve hook callback speed by 30% and add a HOOK_CODE benchmark

---

qemu/target-i386/translate.c
samples/sample_x86.c

Reference Intel software developer manual vol2 Appendix A Table A-6 for
detailed decoding information.
Signed-off-by: vardyh <vardyh.dev@gmail.com>

x86::trans: handle illegal case for opc c6/c7

---

uc.c

It should now return the expected error code when the size specified is not a multiple of 4KB.

uc_mem_unmap returns proper error code & fixes #863

---

tests/unit/test_gdt_idt_x86.c

Fix C syntax mistake in test_gdt_idt_x86.c

---

qemu/cpu-exec.c

Don't clobber EIP after non INT/SYSCALL exception

---

qemu/target-i386/unicorn.c

Previously, every time I tried to get the eflags out of unicorn, it would return zero. This switches to using the methods provided by qemu for correctly manipulating the internal flags to not run afoul of qemu's lazy flags calculation.
I am _extremely_ suspect of the setting of eflags0 - my guess is that it was added as a hack to work around this issue in a different way. Removing the lines setting it causes no regressions in my testing but I have no idea what the effect is deeper in qemu, especially in the translation optimization mechanism.

Use the qemu helpers to get/set the x86 eflags

---

bindings/ruby/unicorn_gem/ext/types.h
bindings/ruby/unicorn_gem/ext/unicorn.c
bindings/ruby/unicorn_gem/unicorn.gemspec

In order to reduce rounding problems from calculations, FPU stack registers for x86 architectures contain values stored in an 80-bit extended precision format.
As a result, reading and writing to these registers requires specific handling.
This update brings the Ruby bindings in line with the Python bindings by supporting reading and writing the FPU stack registers using 2-element arrays: [mantissa, exponent]
The mantissa array element contains the first 64 bits of the FPU stack register.
The exponent array element contains the last 16 bits of the FPU stack register.
Closes #891

Ruby: Support reading and writing x86 FPU stack registers

---

tests/regress/x86_64_msr.py

now that i've learned from #898 and #899  (thanks again @Nukem9), i've put together minimal test cases showing how to set fs and gs on x86-64. this can serve as documentation/example code for future users of unicorn.

add 64-bit test demonstrating setting MSRs and FS/GS segments

---

.travis.yml
Brewfile

prevents issues stemming from brew's "already installed package" error
been using for a while and can recommend

Move to new OSX dependency management system

---

.travis.yml

brew HEAD pulls from master, so it only makes sense to build on master
trusty is now the travis default, explicit jobs are no longer required

only build brew HEAD on master and rm trusty jobs

---

docs/COMPILE-NIX.md

The unit test makefile tries to use "gobjcopy" when assembling tests. This binary isn't present on stock Mac OS X, since it refers to the GNU version of objcopy. It's trivial to install via homebrew (`brew install binutils`) but it isn't mentioned in the Readme for building on *Nix.
I added a note about installing it, as well as cmocka using Homebrew. I also added a note that tests will fail if their architecture support wasn't compiled.

Note about GNU binutils dependency on Mac OS in *Nix readme

---

bindings/ruby/Makefile
bindings/ruby/unicorn_gem/unicorn.gemspec

Hi, 
I changed the name of the gem to unicorn-engine. This name is used when you install the gem from rubygems. 
regards

changed gem name to unicorn-engine

---

include/unicorn/arm64.h

According to the resource following, register aliases UC_ARM64_REG_IP0 and UC_ARM64_REG_IP1 are inversely defined.
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.den0024a/ch09s01s01.html

arm64: IP0 is r16 and IP1 is r17

---

bindings/java/Makefile
bindings/java/Makefile.build
bindings/java/README.TXT

* Fixes the logic for Dylib extensions on macOS.  The logic would previously use the .dll extension instead of .dylib
* Adds an uninstall task and documentation.

Fix Java Makefile on macOS

---

bindings/python/sample_x86.py

Fix naming in Python sample_x86.py

---

qemu/target-i386/translate.c

It can be used if we `goto illegal_op`

Initializes i386 prefix value

---

qemu/target-mips/translate.c

Found by oss-fuzz
Explicit cast to unsigned int is required in order to avoid undefined behavior on left shift hitting the most significant bit

Mips undefined shift fix

---

qemu/target-i386/unicorn.c

When in IA-32e mode (x86 64) the value of the MSR  IA32_EFER (0xC0000080) should have LMA and LME bits set. The following code allow to test the issue:
```python
from unicorn import *
from unicorn.x86_const import *
mu = Uc(UC_ARCH_X86, UC_MODE_64)
CODE = b'\xb9\x80\x00\x00\xc0\x0f2' # mov rcx, 0xC0000080 ; rdmsr
mu.mem_map(0x2000, 0x1000)
mu.mem_write(0x2000, CODE)
mu.emu_start(0x2000, 0x2000 + len(CODE))
print("IA32_EFER = 0x{:X}".format(mu.reg_read(UC_X86_REG_RAX)))
```

i386: set MSR IA32_EFER to correct value at init for IA32e Mode

---

qemu/tcg/tcg-op.h

Fixed conditional move tcg bug (tcg_gen_movcond), which generated an  ALWAYS / NEVER condition despite QEMU not supporting those conditions in the tcg_out part
#1053

Fix for tcg_gen_movcond

---

qemu/target-i386/cpu.h

There seem to be several issues with eflags.
#1005 Trying to set eflags with sti may fail. eflags0, which will not be updated by sti, rewrites eflags when cpu_compute_eflags uses it.  
This also happens with popfl and that's one reason why regress/eflags_noset.c doesn't pass (see issue #252).
This is similar to the fix proposed in issue #313 by @farmdve , d773548 solves the problem he was facing.

changed cpu_compute_eflags to use the updated eflags variable.

---

qemu/target-i386/translate.c
tests/regress/x86_vex.c

Fixes #1062.
Problem was that when decoding an instruction with the VEX prefix, the extension byte was not added.
The fix appears in upstream qemu.

Fixed the decoding of opcodes after getting vex2 using 0xc5

---

include/unicorn/arm.h
qemu/target-arm/unicorn_arm.c

1. Create an enum name for the IPSR register.
2. Implement read and write of the IPSR via the xpsr helper functions.
Fixes #1065

Add support for the ARM IPSR register.

---

include/unicorn/arm.h
qemu/target-arm/unicorn_arm.c

Necessary for NVIC exception emulation from user.

Add ARM MSP, PSP and CONTROL register access

---

bindings/python/unicorn/unicorn.py
qemu/target-i386/unicorn.c

Accessing the ymm8-ymm15 registers so far only returned 0 because they were not handled.
Should I add the following registers the same way?

support for YMM registers ymm8-ymm15

---

docs/COMPILE-NIX.md
make.sh

I noticed that building for Android ARM64 was not an option in make.sh, so here it is.

Add ARM64 Android support in make.sh

---

Makefile

This is necessary for use in python3 virtualenvs. macOS doesn't have a python2 binary, so we have to hardcode the path here to circumvent the virtualenv.

Specify python for building QEMU on macOS

---

.appveyor.yml
.travis.yml
Makefile

@aquynh this should fix msys2 and travis builds
travis has moved to `xenial` by default (now that `trusty` is EOL)

fix msys2 and travis builds

---

qemu/softmmu_template.h
tests/regress/hook_readonly_write_local.py

This is a test and fix for [https://github.com/unicorn-engine/unicorn/issues/1111](https://github.com/unicorn-engine/unicorn/issues/1111)

Check for TLB invalidation after read callback(s).

---

qemu/target-i386/cpu.h
qemu/target-i386/seg_helper.c
qemu/target-i386/unicorn.c
uc.c

close #1117.
Writing the segment registers directly probably cause the emulator crash, and python can not catch the exceptions which runs in C.
Add _uc_check_cpu_x86_load_seg() before run cpu_x86_load_seg(), check the arguments , return error instead of raising exceptions. Python will check the return value, raise local language exception on error.

check arguments, return error instead of raising exceptions. 

---

msvc/samples/mem_apis/mem_apis.vcxproj
msvc/samples/sample_arm/sample_arm.vcxproj
msvc/samples/sample_arm64/sample_arm64.vcxproj
msvc/samples/sample_arm64eb/sample_arm64eb.vcxproj
msvc/samples/sample_armeb/sample_armeb.vcxproj
msvc/samples/sample_batch_reg/sample_batch_reg.vcxproj
msvc/samples/sample_m68k/sample_m68k.vcxproj
msvc/samples/sample_mips/sample_mips.vcxproj
msvc/samples/sample_sparc/sample_sparc.vcxproj
msvc/samples/sample_x86/sample_x86.vcxproj
msvc/samples/sample_x86_32_gdt_and_seg_regs/sample_x86_32_gdt_and_seg_regs.vcxproj
msvc/samples/shellcode/shellcode.vcxproj
msvc/unicorn/aarch64-softmmu/aarch64-softmmu.vcxproj
msvc/unicorn/aarch64eb-softmmu/aarch64eb-softmmu.vcxproj
msvc/unicorn/arm-softmmu/arm-softmmu.vcxproj
msvc/unicorn/armeb-softmmu/armeb-softmmu.vcxproj
msvc/unicorn/m68k-softmmu/m68k-softmmu.vcxproj
msvc/unicorn/mips-softmmu/mips-softmmu.vcxproj
msvc/unicorn/mips64-softmmu/mips64-softmmu.vcxproj
msvc/unicorn/mips64el-softmmu/mips64el-softmmu.vcxproj
msvc/unicorn/mipsel-softmmu/mipsel-softmmu.vcxproj
msvc/unicorn/sparc-softmmu/sparc-softmmu.vcxproj
msvc/unicorn/sparc64-softmmu/sparc64-softmmu.vcxproj
msvc/unicorn/unicorn/unicorn.vcxproj
msvc/unicorn/unicorn_static/unicorn_static.vcxproj
msvc/unicorn/x86_64-softmmu/x86_64-softmmu.vcxproj

Updates the MSVC projects to compile with the Default Platform tool set for the installed compiler, rather than a hard requirement for v110_xp.
This allows Unicorn to compile with current versions of Visual Studio, without requiring additional installation of an older tool set.

msvc: Use default platform toolset

---

msvc/samples/sample_x86/sample_x86.vcxproj
msvc/unicorn/aarch64-softmmu/aarch64-softmmu.vcxproj
msvc/unicorn/aarch64eb-softmmu/aarch64eb-softmmu.vcxproj
msvc/unicorn/arm-softmmu/arm-softmmu.vcxproj
msvc/unicorn/armeb-softmmu/armeb-softmmu.vcxproj
msvc/unicorn/m68k-softmmu/m68k-softmmu.vcxproj
msvc/unicorn/mips-softmmu/mips-softmmu.vcxproj
msvc/unicorn/mips64-softmmu/mips64-softmmu.vcxproj
msvc/unicorn/mips64el-softmmu/mips64el-softmmu.vcxproj
msvc/unicorn/mipsel-softmmu/mipsel-softmmu.vcxproj
msvc/unicorn/sparc-softmmu/sparc-softmmu.vcxproj
msvc/unicorn/sparc64-softmmu/sparc64-softmmu.vcxproj
msvc/unicorn/unicorn/unicorn.vcxproj
msvc/unicorn/unicorn_static/unicorn_static.vcxproj
msvc/unicorn/x86_64-softmmu/x86_64-softmmu.vcxproj
qemu/include/hw/qdev-core.h
qemu/include/qom/cpu.h
qemu/include/qom/object.h
qemu/qom/object.c
uc.c

- typename, class, and class are all keywords for MSVC. Adding a suffix to all of them to avoid potential conflicts.
- Switching program database options for DEBUG builds from /ZI to /Zi to avoid crashes at longjmps (see [explanation](https://developercommunity.visualstudio.com/content/problem/282418/unicorn-library-crashes-when-calling-longjmp-and-c.html)).
Successfully compiled and tested under VC 2017 (15.9) after upgrading the build target to v141_xp. Confirmed with @rhelmot and got her approval.

Two fixes to get unicorn build better with MSVC.

---

msvc/README.TXT
msvc/unicorn/unicorn/unicorn.vcxproj
msvc/unicorn/unicorn_static/unicorn_static.vcxproj

- Quote filepaths in post-build scripts so it can work for dumbasses like me with spaces in their usernames
- Update README with more maintenance advice
After this we can release 1.0.2.

Final tweaks to MSVC build

---

bindings/python/unicorn/unicorn.py
include/unicorn/unicorn.h
uc.c

The `context_save`, `context_update` and `context_restore` API of Unicorn are using directly C pointers in the bindings, that makes the result of a `context_save` unserializable.
The goal here is to be able to save the context of a cpu, write this state on the disk, and load this cpu context in another emulator of the same architecture and mode.
In simple words, be able to have a CPU snapshot across emulators.
This PR is a fix for the Python bindings. It doesn't break the API for other bindings.
Since the cpu context is just a big buffer, we can let the Python allocate the buffer, and pass it to `uc_context_save` function that will fill it with the cpu context data.
To be able to do this, we need to expose the `cpu_context_size` function to the bindings.
We can then let the Python handle …

Handle serialization of cpu context save

---

qemu/target-i386/unicorn.c

fix oss-fuzz issue 10334: unicorn/fuzz_emu_x86_32: Direct-leak in g_malloc.

fix oss-fuzz issue 10334

---

bindings/python/setup.py

Allows `python setup.py bdist_wheel` on windows to properly build and distribute its own binaries under the new configuration.

Python packaging logic for msvc build

---

qemu/cpu-exec.c

Fix the error in the hook_code of the arm, calling emu_stop and causing the pc value to be incorrect after the end of the run.
poc :
```
from unicorn import *
from unicorn.arm_const import *
def hook_fuc(mu, addr, size, data):
pc = mu.reg_read(UC_ARM_REG_PC)
print("hook pc is : 0x%x" % pc)
if pc == 0x8034:
mu.emu_stop()
CODE_ADDRESS = 0x8000
code = '''
mov r0, 0
bl fuc1
nop
nop
bl fuc2
nop
nop
bl fuc3
nop
nop
b end
fuc1:
add r0, 1
add r0, 1
bx lr
fuc2:
add r0, 2
add r0, 2
bx lr
fuc3:
add r0, r0
add r0, r0
bx lr
end:
nop
nop
'''
code = b'\x00\x00\xa0\xe3\x08\x00\x00\xeb\x00\xf0 \xe3\x00\xf0 \xe3\x08\x00\x00\xeb\x00\xf0 \xe3\x00\xf0 \xe3\x08\x00\x00\xeb\x00\xf0 \xe3\x00\xf0 \xe3\x08\x00\x00\xea\x01\x00\x80\xe2\x01\x00\x80\xe2\x1e\xff/\xe1\x02\x00\x80\xe2\x02\x00\x80\xe2\x1e\xff/\xe1\x00\x00\ …
```

Calling emu_stop in the hook_code of the arm causes the pc to be inconsistent.

---

bindings/python/setup.py

`msbuild`-based build doesn't actually work outside of windows. msbuild on mac and linux only works for C# programs I'm pretty sure.
see #1100

restrict msbuild to win32 platform

---

qemu/target-i386/ops_sse.h

fix oss-fuzz issue 10578.
Issue 10578: unicorn/fuzz_emu_x86_32: Crash in helper_pcmpestrm_xmm.

fix oss-fuzz issue 10578.

---

include/uc_priv.h
include/unicorn/unicorn.h
samples/sample_x86.c
tests/unit/test_x86.c
uc.c

I was working on a project where I had to measure generated code and noticed that I had no way of telling if the code runs for infinite time so I had to implement it myself, this PR is a side effect of my needs and maybe it provides to be useful in the main code base. This PR implements a new error code UC_ERR_TIMEOUT, to do that I had to add a new state variable which is reset in uc_emu_start and set in the timeout thread function. I also adjusted the sample to reflect the new change.

Timeout error

---

qemu/cpu-exec.c

Under some circumstances, the PC is not fixed up properly when
returning from the execution of a block in cpu_tb_exec. This appears
to be caused by the resetting of the PC from the tb.
This change removes the additional fixup in the cases where there
is code tracing or timing active. Either of these cases would result
in the wrong PC being reported.
Closes unicorn-engine#1105.

Ensure that PC is not fixed up when code tracing or timing.

---

qemu/target-arm/unicorn_arm.c

The SPSR register is named within the Unicorn headers, but the code
to access it is absent. This means that it will always read as 0 and
ignore writes. This makes it harder to work with changes in processor
mode, as the usual way to return from a CPU exception is a
`MOVS pc, lr` for undefined instructions or `SUBS pc, lr, #4`
for most other aborts - which implicitly restores the CPSR from SPSR.
This change adds the access to the SPSR so that it can be read and
written as the caller might expect.

Add implementation of access to the ARM SPSR register.

---

qemu/scripts/ordereddict.py

Python 3.8 moved some types from `collections` to `collections.abc`.

Python 3.8 compatibility

---

Makefile
bindings/python/setup.py

libunicorn.dylib is currently installed on macOS as unversioned but its install name is versioned and lacking an @rpath, making it difficult to use from clients without modifying it with `install_name_tool`. This change makes it easier to link against because now binaries that want to do so can adapt *their* `LC_RPATH` to match Unicorn's install location and the actual library does not have to be modified. See https://github.com/angr/angr/pull/1932 for how this is being used.

Make it easier to link against libunicorn on macOS

---

qemu/tcg/optimize.c
qemu/tcg/tcg.c

`typedef uint64_t tcg_target_ulong;
typedef tcg_target_ulong TCGArg;
TCGArg *args`
`} else { do_reset_output: for (i = 0; i < nb_oargs; i++) { if (args[i] < 0 || args[i] >= TCG_MAX_TEMPS) {`
`if (!(def->flags & TCG_OPF_SIDE_EFFECTS) && nb_oargs != 0) { for(i = 0; i < nb_oargs; i++) { for(i = 0; i < nb_oargs; i++) { if (args[i] < 0 || args[i] >= TCG_MAX_TEMPS) {`
The expression(args[i] < 0) always returns false.So i deleted it

The expression(args[i] < 0) always returns false

---

bindings/python/setup.py

Installing the python binding with python2 errors as the `shutil.copy` function doesn't have this parameters[1].
[1] https://docs.python.org/2.7/library/shutil.html

fix binding install on python2

---

qemu/cpu-exec.c

Ensure the TCG exit flag is cleared at the end of cpu_exec. This ensures
that subsequent calls are not polluted by the prior call to request an
early exit. The symptoms of the problem being addressed here are that
after a cpu_exit call triggered within a hook there may still be a
pending tcg_exit_req flag set. This then causes a block to start its
execution and then be aborted (from which point it'll continue because
there's no other condition to service). The start of the execution
causes the block hook to be called, no actual code to be run, and then
the block started again with another block hook call.
This change is discussed in ticket 1193:
https://github.com/unicorn-engine/unicorn/issues/1193

Fix block hooks being called twice after an early exit from execution.

---

include/uc_priv.h

This change removes the check for stop requests from the hook loop
macro.
Requests to stop emulation (uc_emu_stop) should only affect whether
the emulation stops. This isn't the case at present for the invocation
of hooks. If emulation is requested to be stopped (which is indicated
by `uc->stop_request`), the hooks will skip all execution. This means
that when the emulation stop is requested, some expected operations
may not occur before the emulation exits - leaving the system in an
inconsistent or broken state.
This is particularly obvious in the case where a CPU interrupt is
required, and a hook has been registered for such cases. The expected
operation is that the hook be called, and no CPU exception be raised
(because the hook has handled it). However, because of the short-cut
in the …

Ensure that hooks are unaffected by a request to stop emulation.

---

include/unicorn/arm64.h
qemu/target-arm/unicorn_aarch64.c

Hi,
I've added the following registers to the API:
* PSTATE
* Exception link registers (ELR_ELx)
* Stack pointers registers (SP_ELx)
* MMU (TTBRn_EL1)
* Exception syndrom registers (ESR_ELx)
* Faulting virtual address registers (FAR_ELx)
* PAR (PAR_EL1)
* MAIR (MAIR_EL1)
* Vector base address registers (VBAR_ELx)

Aarch64: Add some cool registers to the API

---

qemu/target-ppc/cpu.h
qemu/target-ppc/translate_init.c

This aims to fix #1269 (PowerPC fails to build with MSVC). The problems found are:
1. Enums are 32bit when compiled by MSVC (because Windows uses LLP64, not LP64, so ints are 32 bits wide), so enum definitions that contain enumerations with values wider than 32bits have been changed to be macros instead.
2. MSVC is has different names for some functions that GCC has.
3. The MSVC preprocessor is basically broken in places, so worked around that.
4. MSVC doesn't understand GCC function attributes.

Make MSVC happy with the new PowerPC code

---

CMakeLists.txt

Option `UNICORN_BUILD_SHARED` added, default value `ON` to stay backward compatible. Set it to `OFF` to build unicorn as a static library.

cmake: add option to build unicorn as a static library

---

CMakeLists.txt

**Steps to reproduce**
Inside a fresh cloned repository, run the following commands which will generate a `unicorn.sln` file into the build folder.
```
mkdir build
pushd build
cmake -G "Visual Studio 16 2019" ..
```
Then, open the `unicorn.sln` file with Visual Studio 2019 and build unicorn.
**Expected result**
- unicorn is built without errors
**Actual result**
```
c1 : fatal error C1083: Cannot open source file: 'aarch64.h': No such file or directory
c1 : fatal error C1083: Cannot open source file: 'mips.h': No such file or directory
c1 : fatal error C1083: Cannot open source file: 'mips64.h': No such file or directory
c1 : fatal error C1083: Cannot open source file: 'mips64el.h': No such file or directory
c1 : fatal error C1083: Cannot open source file: 'mipsel.h': No such file or …
```

cmake: fix Visual Studio build

---

CMakeLists.txt

linking of samples like sample_arm do fail due to cyclic references in
the archives
<details><summary>Failing log for reference</summary>
```
[1/2] : && /usr/lib/ccache/bin/clang   -rdynamic CMakeFiles/sample_arm.dir/samples/sample_arm.c.o  -o sample_arm  libunicorn.a  -lpthread  libarm-softmmu.a  libarmeb-softmmu.a  -lm && :
FAILED: sample_arm 
: && /usr/lib/ccache/bin/clang   -rdynamic CMakeFiles/sample_arm.dir/samples/sample_arm.c.o  -o sample_arm  libunicorn.a  -lpthread  libarm-softmmu.a  libarmeb-softmmu.a  -lm && :
/usr/bin/x86_64-unknown-linux-musl-ld: libarm-softmmu.a(tcg.c.o):(.data.rel.ro+0x2f88): undefined reference to `helper_div_i32'
/usr/bin/x86_64-unknown-linux-musl-ld: libarm-softmmu.a(tcg.c.o):(.data.rel.ro+0x2fa0): undefined reference to `helper_rem_i32' …
```

cmake: fix static linking due to cyclic deps

---

.travis.yml

cmake static build failed with error [message](https://travis-ci.com/github/chfl4gs/unicorn/jobs/343337504#L242)
Travis-CI cmake version 3.12.4
```
CMake Error at CMakeLists.txt:924 (install):
install TARGETS given no ARCHIVE DESTINATION for static library target
"unicorn".
-- Configuring incomplete, errors occurred!
```

Adding Travis-CI cmake static build

---

.github/workflows/python-publish.yml
bindings/python/build_wheel.sh
bindings/python/setup.py

**Purpose:**
Utilizing github action to build and publish python distribution packages including source package to pypi.org  on repo [tag]. Build will still be triggered on [push].
Binary distribution packages:
sdist, win32, win-amd64, manylinux1_x86_64, manylinux_i686, macos_x86_64
**Preparation:**
1. Go to https://pypi.org/manage/account/#api-tokens and create a new API token for the Unicorn project on PyPI, limit the token scope to just this project. You can call it something like GitHub Actions CI/CD or anything that can be easily distinguishable in the token list. Don’t close the page just yet — you won’t see that token again.
2. In a separate browser tab or window, go to the Github Settings tab of unicorn-engine/unicorn repository and then click on Secrets in the left sidebar.
3. …

adding pypi workflow

---

CMakeLists.txt

this e.g. happens if you would try to compile this like this:
cmake -B build
cmake --build build --config Release
@scribam Should fix the remaining CI failures of https://github.com/Vita3K/Vita3K/pull/727

cmake: fix build if workdir is outside of CMAKE_BINARY_DIR

---

.github/workflows/python-publish.yml
.travis.yml

A minor typo on github action step for publishing to pypi.org. It should be **user** instead of **username**. My bad.
```
uses: pypa/gh-action-pypi-publish@master
with:
user: __token__
password: ${{ secrets.pypi_pass }}
packages_dir: ${{ github.workspace }}/bindings/python/dist/
```

Fixing minor typo on PyPI distribution workflow

---

qemu/target-i386/fpu_helper.c

FSTENV and FNSTENV instruction in 64-bit and 32-bit mode should be handled in the same way.
https://stackoverflow.com/a/50460464/11790783

fix 64-bit fstenv

---

qemu/target-arm/unicorn_arm.c
tests/regress/arm_apsr_access.py

- Q flag / GE flag were not included in APSR register (read/write)
- UC_ARM_REG_APSR_NZCV register constant was ignored completely.
- regression test added

fix an issue with ARM APSR register handling

---

.travis.yml
bindings/python/setup.py
qemu/target-i386/fpu_helper.c

1. zip_safe to False on python binding as contains binary lib. Some older OS might not able to use zipped egg with binary lib.
2. Fixing python binding build and installation under cygwin, correcting lib filename and path.
3. Adjusting travis-ci cache, and temporarily disabling unittest on cmake static build.
4. disabling unittest on cygwin clang as cmocka does not build properly.

Fixing installation on cygwin, Travis-ci cache adjustment

---

include/uc_priv.h

When you uc_emu_start with count more than 0 and then uc_emu_start with count = 0, to be deleted hooks are not processed yet (because it's processed at the end of uc_emu_start) still have effects. 
Because of this issue, code hook internally inserted by unicorn to count the instructions are not really deleted when we uc_emu_start with count = 0. This "leftover" hook inserted monitoring tcg between every instruction and resulted in the hang described in https://github.com/unicorn-engine/unicorn/issues/1313, even if we didn't add any code hook.
This PR fixes this issue by checking to_delete field in HOOK_BOUND_CHECK, so that unicorn can ignore to be deleted hooks.

Fix enabled hooks even after deleting them

---

qemu/include/exec/ram_addr.h
qemu/include/qemu/bitmap.h
qemu/util/bitmap.c

When unicorn and systemd are combined into a single binary the 2
libraries conflict on bitmap_set and bitmap_clear functions which breaks
unicorn.

Add qemu_ prefix to bitmap_set and bitmap_clear to avoid conflicts.

---

qemu/include/qemu/bitmap.h
qemu/util/bitmap.c

When unicorn and systemd are included into a single binary they conflict
on the bitmap_clear function which breaks unicorn. It seems that
long-term we can remove the qemu_bitmap_clear altogether and leave only
bitmap_zero_extend.

Removed unused bitmap_set rename bitmap_clear to qemu_bitmap_clear.

---

bindings/rust/README.md
bindings/rust/src/ffi.rs
bindings/rust/src/lib.rs
bindings/rust/src/unicorn_const.rs
bindings/rust/src/utils.rs
bindings/rust/tests/unicorn.rs

* Added basic block hooking
* Changed confusing struct naming. Before: Protection::All -> R,W,X, Now: Permission::All -> R,W,X
* Fixed issue with remove_hook(..). Implementation tried to remove hook from incorrect hashmap.
* Made unused private vmmap(..) public.

Improved Rust bindings

---

bindings/python/sample_x86.py

Caused by fbef45b18f2f59d9699af54c6ad6ac73eaba3b29.
Now the code assumes if it completes without an error, it was successful.

Fix failing test caused by removal of UC_ERR_TIMEOUT

---

qemu/target-mips/unicorn.c

```python
from unicorn import *
from unicorn.mips_const import *
MIPS_CODE_EL = b"".join([
b"\xad\xde\x02\x3c", # lui   $v0, 0xdead
b"\xef\xbe\x42\x34", # ori   $v0, $v0, 0xbeef
b"\xad\xde\x03\x3c", # lui   $v1, 0xdead
b"\xef\xbe\x63\x34", # ori   $v1, $v1, 0xbeef
b"\x19\x00\x43\x00", # multu $v0, $v1
])
ADDRESS = 0x10000
mu = Uc(UC_ARCH_MIPS, UC_MODE_MIPS32 + UC_MODE_LITTLE_ENDIAN)
mu.mem_map(ADDRESS, 2 * 1024 * 1024)
mu.mem_write(ADDRESS, MIPS_CODE_EL)
mu.emu_start(ADDRESS, ADDRESS + len(MIPS_CODE_EL))
print(">>> Emulation done. Below is the CPU context")
lo = mu.reg_read(UC_MIPS_REG_LO)
print(">>> LO = 0x%x" % lo) # should be 0x216da321
hi = mu.reg_read(UC_MIPS_REG_HI)
print(">>> HI = 0x%x" % hi) # should be 0xc1b1cd12
```
considering the code above, LO and HI will be always zero due …

fix HI/LO register read/write issue in MIPS

---

CMakeLists.txt
msvc/unicorn/unicorn/unicorn.vcxproj
msvc/unicorn/unicorn/unicorn.vcxproj.filters
msvc/unicorn/unicorn_static/unicorn_static.vcxproj
msvc/unicorn/unicorn_static/unicorn_static.vcxproj.filters
qemu/include/sysemu/os-win32.h
qemu/util/setjmp-wrapper-win32.asm

Short answer: Windows default implementation of setjmp/longjmp is incompatible with jit generated code.
A longer answer: https://blog.lazym.io/2020/09/21/Unicorn-Devblog-setjmp-longjmp-on-Windows/.
Note that x86 setjmp/longjmp is implemented without RtlUnwind so there is no need to modify that.

Fix setjmp/longjmp on native Windows

---

bindings/python/sample_x86.py
bindings/python/unicorn/unicorn.py
uc.c

1. Fix `uc_context` size in uc.c.
2. Make `UcContext` convertible to bytes.
3. Make `UcContext` picklable.
4. Fix `context_update` in python bindings.

Fix context saving

---

CREDITS.TXT
bindings/python/unicorn/unicorn.py
include/uc_priv.h
include/unicorn/unicorn.h
uc.c

This PR follows #1335.
WARNING: This PR introduces a break change: contexts allocated by `uc_context_alloc` now should be free-ed by `uc_context_free`. uc_free() the contexts will still work in some scenarios, but the result is undefined.

Implement uc_context_free

---

uc.c

This allows us to build LE-only ARM unicorn variants

Fix compile if HAS_ARM is defined but HAS_ARM_EB isn't

---

qemu/include/qemu-common.h

Conflicting symbols need to be undefined before including altivec.h.
Without it, build fails with:
`error: unknown type name 'vector'`

Fix build with LLVM on powerpc64(le)

---

bindings/java/Makefile.build

Hi, I was having trouble building java bindings on latest ubuntu. I installed jdk8 which has javah but somehow was failing during install (missing compiled classes even if they were in place in unicorn/). I guess mixing with jdk11 pop the issue. 
Using javac from most recent jdk works very fine.

Remove deprecated javah and build with javac

---

qemu/target-arm/translate.c

A fix to issue #853 where restarting the emulator during ITE instructions would lead to incorrect operations.
While there seems to be code addressing the topic using condexec_bits, locating their underlying issue may be a better fix for another time. This solution ignores tracing instructions within ITE blocks (where condexec_mask should be greater than zero) and on IT instructions which prevents emulation from halting and breaking the code.

Fix pausing within Thumb2 ITE blocks (#853)

---

CMakeLists.txt

Did my best to modernize the CMake a bit and add options for installation/samples, which will allow users to add unicorn to their CMake projects by doing `add_subdirectory` (or FetchContent). Everything is backwards compatible and when installing unicorn I get the same outputs.
Example project that automatically downloads and compiles unicorn: https://github.com/mrexodia/unicorn_template

Modernize CMake

---

samples/sample_arm.c

This one fixes the sample submitted in #1381.

The UC instance must be created twice to reproduce the problem

---

bindings/python/unicorn/unicorn.py
tests/regress/hook_raises_exception.py

Closes #1386.
If a hook raises an exception, a call to `emu_stop()` is issued. Before `emu_start()` returns, it will check for an outstanding exception and raise it.

Handle exceptions raised in Python hook functions

---

CREDITS.TXT
qemu/target-i386/fpu_helper.c

ST0 gets overwritten with 0.0 whenever FTST is executed.

X86 instruction FTST was incorrectly overwriting ST0 instead of FT0

---

CMakeLists.txt
include/unicorn/platform.h

Compiling with Win32 Release/MinSizeRel/RelWithDebInfo in VS2008 will cause "fatal error C1063: compiler limit: compiler stack overflow" problem.
Compiling with Win32 Debug or x64 does not have this problem.
You can easily bypass this problem by changing the optimization options /O1 and /O2 to /Od.
In VS2010, when _INTPTR is 0 or 1, UINTPTR_MAX is 0xFFFFFFFF.

compile on VS2008/VS2010

---

bindings/rust/build.rs

With uc2, the bindings no longer use the surrounding unicorn checkout, but download the unicorn instance.
Sadly, this happens with every build, so changing a single line in your script takes 5 minutes to build...
This PR changes this to only download once.

No redownload in rust bindings

---

tests/unit/test_mem.c

This adds the test case mentioned in #1497 as a unit test.
Feel free to close this, if unmapping parts of MMIO regions is intentionally not supported.

Add test case for #1497

---

bindings/go/unicorn/uc.c
bindings/go/unicorn/uc.h
bindings/go/unicorn/unicorn.go

I added a `SetCPUModel` method to the unicorn interface in the go bindings to address #1502. CGO does not support calling C functions with varargs so I also added a `uc_ctl_set_cpu_model_helper` function to `uc.c` to call `uc_ctl`
Usage:
`
emu, _ := uc.NewUnicorn(uc.ARCH_M68K, uc.MODE_BIG_ENDIAN)
emu.SetCPUModel(uc.CPU_M68000_CPU)
`

SetCPUModel go binding for setting the CPU model

---

qemu/target-mips/translate.c

This little patch fixes a bug in the QEMU of Unicorn - implementation of the LUI instruction (MIPS) is not correct: the instruction must perform signed extension of the immediate operand, but it is unsigned in the code (probably a misprint); I have fixed it. I also attach the corresponding fragment of the MIPS instruction set reference which describes this instruction.

Bug fix for LUI instruction (MIPS)

---

qemu/target-i386/fpu_helper.c
tests/unit/Makefile
tests/unit/test_x86_fxsave_fpip.c

fxsave / fxsave64 are sometimes used in GetPC type of code in exploits and exploit encoders. This patch provides support for storing the Floating Point Instruction Pointer (fpip) in fxsave / fxsave64, thus enabling such exploit code to be emulated.

fxsave / fxsave64 should store the floating point instruction pointer (fpip)

---

tests/unit/test_arm64.c
tests/unit/test_riscv.c

Hello, when rewriting (what I called code patching) the code memory to change an instruction, the previous instruction will be executed instead. 
In the tests, I wrote an `add 1` to a register, emulated to see the result, then overwrote the instruction with `add 7ff` to the same register and re-emulated. When using the `start_address`/`end_address` method, the execution of the new instruction proceeds however when using a count, the previous instruction is executed instead.

Issues with count for code patching 

---

bindings/python/unicorn/unicorn.py

The pending exception hook is set when the hook raised an exception
and wants to report it outside the emulation loop. However, it is
never cleared back to None. This means that after an exception is
raised in a hook, all subsequent execution (even if successful) will
raise the exception.
This change clears the exception before we start another emulation,
which should ensure that if we have _hook_exception set, it really
is from hooks in this emulation run.

Clear Python pending hook exception before we enter the emulation.

---

bindings/rust/src/ffi.rs
bindings/rust/src/lib.rs
bindings/rust/tests/unicorn.rs

And I do a `cargo fmt` and `cargo clippy` on the code.
* * *
After #1480, remove self inside a hook leads to a segmentation fault. This is the PoC:
```rust
use std::ffi::c_void;
use unicorn_engine::unicorn_const::{Arch, Mode, Permission, SECOND_SCALE};
use unicorn_engine::Unicorn;
static mut STEP_HOOK: Option<*mut c_void> = None;
fn step_hook(uc: &mut Unicorn<()>, _addr: u64, _size: u32) {
unsafe {
if let Some(step_hook) = STEP_HOOK {
uc.remove_hook(step_hook)
.expect("Failed to remove step hook");
STEP_HOOK = None
}
}
}
fn main() {
let x86_code = [
0x48, 0xB8, 0xEF, 0xBE, 0xAD, 0xDE, 0x00, 0x00, 0x00, 0x00, 0x0F, 0x05,
];
let mut uc = unicorn_engine::Unicorn::new(Arch::X86, Mode::MODE_32)
.expect("failed to initialize unicorn instance");
assert_eq!(uc.mem_map(0x1000, 0x4000, …
```

rust: Allow to remove self inside a hook

---

bindings/rust/src/ffi.rs
bindings/rust/src/lib.rs
bindings/rust/src/unicorn_const.rs

After this PR, we can do something likes this:
C code:
```c
#include <unicorn/unicorn.h>
#include "rust_ffi.h"
int main()
{
uc_engine *uc;
int val = 0;
uc_open(UC_ARCH_ARM, UC_MODE_ARM, &uc);
rust_ffi(uc);
uc_reg_read(uc, UC_ARM_REG_R0, &val);
printf("R0: %d\n", val);
uc_close(uc);
return 0;
}
```
Rust code:
```rust
#![allow(non_camel_case_types)]
use std::ffi::c_void;
use std::convert::TryFrom;
pub type uc_handle = *mut c_void;
use unicorn_engine::Unicorn;
use unicorn_engine::RegisterARM;
#[no_mangle]
pub extern "C" fn rust_ffi(handle: uc_handle) {
if let Ok(mut unicorn) = Unicorn::try_from(handle) {
assert_eq!(unicorn.reg_write(RegisterARM::R0, 1234), Ok(()));
} else {
panic!("Failed convert handle to Unicorn")
}
}
```
I think this PR is only meaningful after #1511 is merged, otherwise …

Support to pass unicorn handle to rust through FFI

---

qemu/include/qemu/osdep.h

`Could not allocate dynamic translator buffer` error while
trying to perform any memory-related operation.
This happens on aarch64 (MacBook Pro M1)
Solution: ensure aarch64 architecture is properly checked against
Fixes #1556

Problem: Could not allocate dynamic translator buffer

---

qemu/target/s390x/translate.c

This is a backport of the following upstream commits:
- commit fc3dd86a290a ("s390x/tcg: Fix BRASL with a large negative offset")
- commit 16ed5f14215b ("s390x/tcg: Fix BRCL with a large negative offset")

s390x/tcg: Fix BRASL and BRCL with large negative offsets

---

bindings/rust/src/ffi.rs
bindings/rust/src/lib.rs
bindings/rust/tests/unicorn.rs

The x86 IN callback [uc_cb_insn_in_t](https://github.com/n1tram1/unicorn/blob/c10639fd4658a852049546162d116b123e2b1ec2/include/unicorn/unicorn.h#L231) is supposed to return a u32 (the value from the i/o port).
This fixes that by making the callback return a u32.

Fix rust binding for insn_in hook callback

---

uc.c

If `uc->init_arch == NULL`, uc need to be retruned because it already points to heap space. Of course, we can also directly free the corresponding memory space.
```c
if (uc->init_arch == NULL) {
free(uc);
return UC_ERR_ARCH;
}
```

Fix https://github.com/unicorn-engine/unicorn/issues/1586

---

uc.c

We only need to add simple judgment to prevent integer overflow.
If we apply `0xfffffffffffff000 ~ 0xfffffffffffff000 + 0x1000` like #1590, we will not be able to bypass the memory check!
```shell
Failed on uc_mem_map() with error returned: 15 Invalid argument (UC_ERR_ARG)
```

Fix https://github.com/unicorn-engine/unicorn/issues/1590

---

bindings/python/setup.py

While trying to compile the bindings for Python, I ran into this error
```
luke@DESKTOP-AR7LCLA:~/unicorn-pub/bindings/python$ sudo python3 ./setup.py install
[truncated]
Unknown argument -j4
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
<dir>          = Project binary directory to be built.
-j [<jobs>] --parallel [<jobs>] = Build in parallel using
the given number of jobs. If <jobs> is omitted
the native build tool's default number is used.
The CMAKE_BUILD_PARALLEL_LEVEL environment variable
specifies a default parallel level when this option
is not given.
--target <tgt> = Build <tgt> instead of default targets.
May only be specified once.
--config <cfg> = For multi-configuration tools, choose <cfg>.
--clean-first  = Build target 'clean' first, then build.
(To clean …
```

Fix Python bindings build

---

bindings/python/unicorn/unicorn.py

This functionality seems to be missing for the Python bindings when it was added in these commits https://github.com/unicorn-engine/unicorn/commit/9d8a309fbf688eb20eac224d465b980afbb052d9 https://github.com/unicorn-engine/unicorn/commit/7bb756249a54a2163d5cb65f35b64912451f0752
Not sure if there's anything else that's missing (or incorrect) for the bindings, but this works for me. I mostly followed the pattern of the other callbacks.

python: Support CPUID hooks

---

qemu/target/arm/unicorn_arm.c

This PR adds support for using all types of Arm SIMD registers (Q0–Q15, D0–D31 and S0–S15) in `uc_reg_read` and `uc_reg_write`.

Support reads and writes over all Arm SIMD registers

---

qemu/target/ppc/unicorn.c
tests/unit/test_ppc.c

When writing a value to the CR (conditional register) the order of the nibbles was reversed. I believe the nibble ordering in the `reg_read` is correct, so I correct `reg_write` to maintain the same endianness. Also included a unit test to make sure that the value we write is the value we read out.

Fixed endianness when writing PPC32 CR register.

---

qemu/target/tricore/helper.h
qemu/target/tricore/op_helper.c
qemu/target/tricore/translate.c
qemu/tricore.h
symbols.sh

Issue is described in #1663 
```
from unicorn import *
from unicorn.tricore_const import *
tricore_code = b"\x91\x10\x01\xf8\xd9\xff\xa0\x2f" #movh.a a15,#0x8011;lea a15,[a15]-0x760
ADDRESS = 0x4000
mu = Uc(UC_ARCH_TRICORE,UC_MODE_LITTLE_ENDIAN)
mu.mem_map(ADDRESS, 0x4000,7)
mu.mem_write(ADDRESS,tricore_code)
mu.emu_start(ADDRESS,0,count=2) # pc don't move
r_pc = mu.reg_read(UC_TRICORE_REG_PC)
print(f"after pc {hex(r_pc)}") # pc 0x4000
```
After mu.emu_start, pc is 0x4000 but should be 0x4008.
To solve this problem, use ```gen_save_pc``` to sync pc in function ```tricore_tr_translate_insn```.

fix issue 1663:tricore pc don't move

---

tests/unit/test_mem.c

This fixes a memory leak in test_mem reported by leak sanitizer. See #1682 for details.

Fix leak in test_mem_protect_map_ptr. (#1682)

---

samples/sample_ctl.c

This fixes incorrect argument types passed to uc_ctl_request_cache/uc_ctl_remove_cache in test_uc_ctl_tb_cache (specifically the one in sample_ctl - the one in test_ctl does not have the same issue). See #1683 for details.

Fix for test_uc_ctl_tb_cache. (#1683)

---

qemu/target/ppc/unicorn.c

This frees the TLB buffers on uc_close. See #1680 for details. Test (test_ppc) passes cleanly with LeakSanitizer enabled after this change.

Fix memory leak in PPC target. (#1680)

---

CMakeLists.txt

The current runtime library handling never works. This PR fixes it to work as intended. See #1692 for details.
A cleaner approach would probably be to just raise the minimum required CMake version globally, but I'm not sure what the 'lowest common denominator' OS you support is, so it seemed safer to just do it this way.

Fix MSVC runtime library handling in CMakeLists. (#1692)

---

qemu/target/tricore/unicorn.c

Not sure if there's more stuff I'm missing to free that's not exercised by the test, but at least this gets the ball rolling and fixes the leaks reported when running tricore_sample under LeakSanitizer. Fixes #1681.

Fix memory leaks in TriCore target. (#1681)

---

CMakeLists.txt
tests/unit/test_ctl.c

When ARM target is not enabled, disable the ARM-specific tests in the test suites which are included unconditionally. See #1689 for details.

Disable ARM-specific tests when ARM is unavailable. (#1689)

---

docs/COMPILE.md

Unicorn is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for unicorn and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build unicorn, ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64, UWP, ARM) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and [here](https://github.com/microsoft/vcpkg/blob/master/ports/unicorn/portfile.cmake) is what the port script looks like. We try to keep the library maintained as close as possible to the original library.

Add vcpkg installation instructions

---

tests/unit/test_mem.c

On machines with a page size larger than 4K, the requested memory size in `test_map_big_memory` gets rounded up and overflows to zero.
This PR adds some code to query the page size and adjust the requested memory size accordingly. See also the discussion in #1678 and thanks to @relapids for the initial debugging, which helped me resolve this issue for Debian on mipsel and s390x much more quickly.

Adjust big memory test for host pagesize

---

qemu/include/qemu/atomic.h
qemu/include/qemu/int128.h
qemu/target/ppc/excp_helper.c

Not sure if this is a change you're interested in or not, but figured I'd send it and let you decide. If you don't want this it's fine, it's easy enough for me to maintain my own patchset (though of course I'd prefer not to).
Build example (using latest LLVM + VS2022 targeting x64):
```
PS E:\Dev\unicorn\build> cmake -S ..\repo\ -B . -G Ninja -D CMAKE_C_COMPILER=clang-cl -D CMAKE_BUILD_TYPE=Debug
PS E:\Dev\unicorn\build> cmake --build .
PS E:\Dev\unicorn\build> cmake --build . --target test
```
There are 4 changes here.
1. The `typeof` extension is only available in GNU mode, whereas `__typeof__` is always available in all modes.
2. __int128_t is already defined with Clang, and since it shares the MSVC headers (hence doesn't define CONFIG_INT128) we need to ifdef it out. Alternatively it …

Allow building with clang-cl (using MSVC config) on Windows.

---

bindings/python/unicorn/unicorn.py

Fix type hint of reg_write in Python bindings. (#1706)

---

bindings/python/unicorn/__init__.py

The riscv constants have not been added to the python binding module yet. They thus cannot be imported and used properly.

add riscv constants to python binding module

---

bindings/python/setup.py

This fixes a warning when calling `./setup.py` directly:
```bash
/usr/lib/python3/dist-packages/_distutils_hack/__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
```
This leads to an error down the line, installation seems to fail.
Pip installation still works without this fix, however.

Fix warning and build error for ./setup.py

---

bindings/rust/src/ffi.rs
bindings/rust/src/lib.rs

Fix https://github.com/unicorn-engine/unicorn/issues/1619 by using Weak references.
This works without unsafe, so it should not have the soundness issue of https://github.com/unicorn-engine/unicorn/pull/1632

Fix Rust binding memory leak

---

uc.c

The MemoryRegion already contains a pointer to the RAMBlock. So it is not necesary to search for it.

Do not search for the RAMBlock in split_region

---

bindings/rust/src/lib.rs

The C function uc_mmio_map() allows to add seperate callback functions and userdata for read and write. When the callback functions are NULL unicorn don't try to call this functions.
Previous this patch, when i.e. read_callback was None the callback was set to mmio_read_callback_proxy and the userdata was set to NULL. On a callback the mmio_read_callback_proxy then tried to dereference the userdata and caused a segfault.
fixes #1762

rust only add mmio callback funktion, if callback is requested

---

Cargo.toml
bindings/rust/build.rs

In rust, it is supported to control the arch compilation list, and the default is to compile all.
#1748

Add arch list feature control in Rust

---

.github/workflows/Nuget-publishing.yml
bindings/const_generator.py
bindings/dotnet/UnicornDotNet.sln
bindings/dotnet/UnicornEngine/Binding/BindingFactory.fs
bindings/dotnet/UnicornEngine/Binding/IBinding.fs
bindings/dotnet/UnicornEngine/Binding/MockBinding.fs
bindings/dotnet/UnicornEngine/Binding/NativeBinding.fs
bindings/dotnet/UnicornEngine/Const/Arm.fs
bindings/dotnet/UnicornEngine/Const/Arm64.fs
bindings/dotnet/UnicornEngine/Const/Common.fs
bindings/dotnet/UnicornEngine/Const/M68k.fs
bindings/dotnet/UnicornEngine/Const/Mips.fs
bindings/dotnet/UnicornEngine/Const/Ppc.fs
bindings/dotnet/UnicornEngine/Const/Riscv.fs
bindings/dotnet/UnicornEngine/Const/S390x.fs
bindings/dotnet/UnicornEngine/Const/Sparc.fs
bindings/dotnet/UnicornEngine/Const/TriCore.fs
bindings/dotnet/UnicornEngine/Const/X86.fs
bindings/dotnet/UnicornEngine/ConvertUtility.fs
bindings/dotnet/UnicornEngine/InternalHooks.fs
bindings/dotnet/UnicornEngine/Unicorn.fs
bindings/dotnet/UnicornEngine/UnicornEngine.fsproj
bindings/dotnet/UnicornEngine/UnicornEngineException.fs
bindings/dotnet/UnicornSamples/ShellcodeSample.cs
bindings/dotnet/UnicornSamples/UnicornSamples.csproj
bindings/dotnet/UnicornSamples/X86Sample32.cs

This PR makes a few changes to the dotnet bindings, so it can be packaged as a Nuget.
Additionally it adds a new workflow to automatically publish the .NET bindings as a Nuget package if they changed in `dev` or `master`.
Packages created from `dev` get a suffix, this way they are marked as prereleases and don't change the latest release.
At the moment this workflow only publishes to Github Packages, but this could be changed to also publish to Nuget.org if you want.
You can read more about the necessary steps [here](https://learn.microsoft.com/en-us/nuget/nuget-org/publish-a-package).
To actually make the workflow work a secret [API key](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry#authenticating-to-github-packages) …

Add github workflow to publish Nuget for .NET bindings

---

qemu/target/i386/unicorn.c

The cpuid results are set by the selected cpu.
CLOSES #1787

[x86] don't hardcode cpuid results

---

bindings/dotnet/UnicornEngine/InternalHooks.fs
bindings/dotnet/UnicornEngine/Unicorn.fs

`*HookInternal` objects can be garbage collected, so their reference should be kept somewhere. With this PR, Unicorn object has `_hookInternals` member where all the hook internal objects are stored.
```
Process terminated. A callback was made on a garbage collected delegate of type 'UnicornEngine!UnicornEngine.MemReadHookInternal::Invoke'.
```
And, `MemReadHook` and `MemWriteHook` trampolines have a wrong callback signature. The second argument should be the event type.
https://github.com/unicorn-engine/unicorn/blob/7b8c63dfe650b5d4d2bf684526161971925e6350/qemu/accel/tcg/cputlb.c#L1469

[dotnet] Fix garbage collected hooks and wrong signature

---

.github/workflows/Nuget-publishing.yml

Context: https://github.com/unicorn-engine/unicorn/issues/1631#issuecomment-1445287574
vcruntime dll may have CFG enabled which checks whether `jmp_buf` has a zero value for frame in `longjmp`, but Unicorn is setting the frame value to zero. The problem appears only when CFG is enabled, and .NET programs have CFG opted in by default. As a workaround, use `libcmt` statically rather than using `vcruntime` for .NET binding. Unicorn may need to implement its own `setjmp`/`lonjmp` in the future, but this workaround seems to work for now.

[dotnet] Add /MT flag for nuget package build

---

bindings/dotnet/UnicornEngine/Unicorn.fs

- Use the native `uc_hook_del` call to delete hooks
- Use the native `uc_hook_add` call to add each hook. Now we can install hooks on different address ranges.
- Support hooks of specific address ranges for `AddEventMemHook`, `AddInHook`, `AddOutHook`, `AddSyscallHook`.
This PR does not change the existing interfaces, so users do not need to update their code.

[dotnet] Use native binding calls whenever possible

---

include/uc_priv.h
qemu/softmmu/cpus.c
qemu/target/arm/unicorn_aarch64.c
qemu/target/arm/unicorn_arm.c
qemu/target/i386/unicorn.c
qemu/target/m68k/unicorn.c
qemu/target/mips/unicorn.c
qemu/target/ppc/unicorn.c
qemu/target/riscv/unicorn.c
qemu/target/s390x/unicorn.c
qemu/target/tricore/unicorn.c
tests/unit/test_ctl.c
uc.c

quit_request is for internal use. This means the IP register was updated and qemu needs to rebuild the translation blocks.
stop_request is set by the user (uc_emu_stop) to indecate that unicorn sould stop emulating.
see #1579

difference between stop_request and quit_request

---

uc.c

`find_memory_region` uses a cache index to check whether the most recently used block is the target block, but the index is never set. It looks like it was accidentally removed in this PR: https://github.com/unicorn-engine/unicorn/pull/1414
The cache index is still effective even with the binary search.

Cache index for find_memory_region

---

qemu/softmmu/memory.c

This fixes build errors introduced by bbbc7856accbae7697db84d10a28c5a6aec81856

use int128_get64 in memory_unmap

---

bindings/rust/src/ffi.rs
bindings/rust/src/lib.rs
bindings/rust/src/unicorn_const.rs
tests/rust-tests/main.rs

This PR adds a wrapper for the uc_ctl function to unicorn's Rust bindings. Since Rust neither allows overloading of functions let alone variadic functions the implementation may seem a bit odd. I'm open to suggestions if you know of a better way to implement this. At the moment the uc_ctl function takes at most two optional arguments that are either a pointer or value that fits into 64-bit of memory. Consequently we need three functions in the Rust bindings to represent these cases. Since the uc_ctl functions does not define any type for the optional arguments it is hard to define a meaningful function signature with Rust being strongly typed. I defined the arguments as void pointers which means that arguments passed to this function first need to be unsafely transmuted. The other option …

add rust bindings for uc_ctl

---

bindings/python/sample_ctl.py
bindings/python/unicorn/unicorn.py

`sample_ctl.py` was not running correctly. It was crashing with various errors: `TypeError: Uc.ctl_remove_cache() missing 1 required positional argument: 'end'`, `KeyError: 64`. This patch fixes the relevant errors in the bindings and scripts.

Fix sample_ctl.py

---

qemu/accel/tcg/cputlb.c
tests/unit/test_x86.c

The load_helper is sometimes called from register writes. When the load fails check if emulation is running before jump out of the emulated code.
see #1828

load_helper only call cpu_loop_exit() when emulation is running

---

.github/workflows/Nuget-publishing.yml

Currently nuget publishing for x86 ubuntu workflow is failing to install required packages.
https://github.com/unicorn-engine/unicorn/actions/runs/5028417981/jobs/9019092076
Run `apt update` to make sure.

Run apt update in nuget publishing workflow

---

qemu/accel/tcg/cputlb.c

callbacks work on the physical address.
As far as I see this is the only case I have add this mistake, but would be nice when someone else could double check.

fix UC_MEM_WRITE_PROT callback

---

bindings/rust/src/lib.rs

This PR fixes multiple `warning: private item shadows public glob re-export` warnings caused by an unnecessary use statement

Fix rust compiler warnings

---

Cargo.toml
bindings/rust/src/lib.rs
bindings/rust/src/unicorn_const.rs

This PR fixes a few clippy warnings caused by an outdated bitflags crate. Also adds two allow annotations for the raw pointer handles.

Fix clippy warnings

---

qemu/target/i386/translate.c

target/i386: fix operand order for PDEP and PEXT
For PDEP and PEXT, the mask is provided in the memory (mod+r/m) operand, and therefore is loaded in s->T0 by gen_ldst_modrm. The source is provided in the second source operand (VEX.vvvv) and therefore is loaded in s->T1. Fix the order in which they are passed to the helpers.

Backport qemu/qemu@75b208c

---

bindings/rust/src/ffi.rs
bindings/rust/src/lib.rs

The current api exposes raw pointers to the user. This change wraps the internal pointer type into a public facing type. This avoids direct use of the ffi for normal api use. Using the ffi directly is still possible.

fix: Wrap uc_hook to not expose ffi types in public api

---

bindings/rust/src/lib.rs
qemu/accel/tcg/cputlb.c
tests/unit/test_mem.c

Title is mostly self explanatory. There was an issue where performing snapshots with a non one to one mapping of virtual to physical addresses, resulting in an assertion failure in unicorn. I assume this commit fixes the issue. @PhilippTakacs should check if this is correct now.

fix: Use correct addresses during memory cow

---

bindings/ruby/unicorn_gem/ext/unicorn.c
qemu/accel/tcg/cputlb.c
samples/mem_apis.c
samples/sample_arm.c
samples/sample_arm64.c
samples/sample_batch_reg.c
samples/sample_ctl.c
samples/sample_x86.c
samples/sample_x86_32_gdt_and_seg_regs.c
tests/regress/00opcode_uc_crash.c
tests/regress/arm_enable_vfp.c
tests/regress/block_test.c
tests/regress/eflags_noset.c
tests/regress/eflags_nosync.c
tests/regress/emu_clear_errors.c
tests/regress/hook_extrainvoke.c
tests/regress/map_crash.c
tests/regress/map_write.c
tests/regress/mips_kseg0_1.c
tests/regress/sigill.c
tests/regress/sigill2.c

This PR fixes some C syntax issues which are deprecated in modern C standards and will eventually lead to build failures with modern compiles like Clang. For details see:
* https://wiki.gentoo.org/wiki/Modern_C_porting
* https://bugs.gentoo.org/879685

Fix deprecated C syntax

---

qemu/target/i386/fpu_helper.c
tests/unit/test_x86.c

This is the same fix (and tests) that was merged in unicorn v1 (see https://github.com/unicorn-engine/unicorn/commit/63a445cbba18bf1313ac3699b5d25462b5d529f4/) now ported to unicorn v2. The fix makes sure that the fxsave x86/x64 instruction saves the instruction pointer (instead of zero) into the floating point context dump. This instruction is used in many modern polymorphic shellcodes. This is a new pull request, this time based on the dev branch.

fix fxsave fpip value, provide tests

---

qemu/include/tcg/tcg-op.h
qemu/target/arm/translate.c

follow-up to #1904 to target `dev` branch instead of `master`
For the fix in `tcp-op.h`:
```
SanitizerError
UndefinedBehaviorSanitizer: out-of-bounds-index unicorn/qemu/include/tcg/tcg-op.h:49:9 in
Details unicorn/qemu/include/tcg/tcg-op.h:49:9: runtime error: index 66 out of bounds for type 'int[17]'
#0 0x7f0637b2656d in gen_uc_tracecode unicorn/qemu/include/tcg/tcg-op.h:49:9
#1 0x7f0637b98b72 in thumb_tr_translate_insn unicorn/qemu/target/arm/translate.c
#2 0x7f0637adef12 in translator_loop_arm unicorn/qemu/accel/tcg/translator.c:124:9
#3 0x7f0637b21df6 in gen_intermediate_code_arm unicorn/qemu/target/arm/translate.c:11775:5
#4 0x7f0637adc01b in tb_gen_code_arm unicorn/qemu/accel/tcg/translate-all.c:1636:5
#5 0x7f0637ac3dbc in tb_find unicorn/qemu/accel/tcg/cpu-exec.c:259:14
#6 …
```

qemu: fix UBSAN errors in tcg and arm translation

---

qemu/target/ppc/translate_init.inc.c
tests/unit/test_ppc.c

Issue #1909 
Access to TB, DEC (time-related) Special Purpose Registers led to crash.
`spr_read_decr`, `spr_write_decr` and others are changed to `spr_read_generic` and `spr_write_decr`.
So spr read/write won't call Qemu time-related functions.

Fix PPC32 fault when timer-spr access

---

qemu/softmmu/memory.c
uc.c

memory_cow expect the address and size to be aligned on pagesize.

fix cow when using uc_mem_write

---

tests/unit/test_mem.c
uc.c

I missed a bug in my last fix.
uc->target_page_align is a uint32_t. When the binary not will only invert the 32 bit of the value. Used this in a binary and operator with a uint64_t will case the upper 32bit of the address to be 0. Therefor the bug only appears when the upper 32bit of the address are used.
Now a local uint64_t variable is used for the alignemend and the test uses a not page alligned address which does not fit in 32bit.

fix uc_mem write with cow when using upper half of the address

---

qemu/tcg/tcg-op.c

This fix makes non-atomic versions of min/max operations aware of sign extension.
The following piece of RISC-V assembly was producing bogus results:
```asm
la a0, .d
li a2, 1
amomin.w a5, a2, (a0)
lw a6, 0(a0)
.d:
.word -1
```
The expected result in `a6` is `-1` but without the fix the result is `1`

Backport from qemu : fix do_nonatomic_op_* vs signed operations

---

bindings/python/sample_x86.py
bindings/python/shellcode.py
tests/regress/hang.py
tests/regress/hook_readonly_write_local.py
tests/regress/jmp_ebx_hang.py

Noticed an errant semicolon while looking at the x86 sample and was curious if there were more so just cleaned a few more up real quick.

Remove semicolons in python files

---

bindings/rust/src/lib.rs
tests/rust-tests/main.rs

The block hook was missing start and end parameters to limit the address range of the hook.

Feature: Bindings: add start end to block hook

---

bindings/rust/src/ffi.rs
bindings/rust/src/lib.rs
bindings/rust/src/unicorn_const.rs

This is split into 2 commits
- apply default rust 2021 formatting to entire rust codebase
- conditionally include rust code based on the compilation bindings / features set when used in cargo.toml

Rust conditional compilation

---

.github/workflows/PyPI-publishing.yml
bindings/python/setup.py
bindings/python/unicorn/unicorn_py2.py

New `unicorn_py3` folder is not installed when running `setup.py install`, making unicorn unable to be imported (`import unicorn`) when using Python 3, see error message attached. Double asterisk for recursiveness because inside the folder has `arch` folder also.
Without `unicorn_py3/*`
Without double asterisk

Add unicorn_py3 folder to setup.py

---

.github/workflows/zigbuild.yml
bindings/zig/README.md
bindings/zig/sample/sample_riscv_zig.zig
build.zig
build.zig.zon

The latest tagged zig release is `0.12.0` <https://ziglang.org/download/0.12.0/release-notes.html>, this pr does a few things:
- updates the zig bindings to be compatible with zig 0.12.0
- cleans up the `build.zig` code
- makes the zig ci pass
- make unicorn be usable by the [Zig Build System](https://ziglang.org/learn/build-system/)
I plan on pushing more cleanup pr's to the zig stuff and make an actual "zig-style" api

Update Zig bindings to Zig 0.12.0

---

tests/unit/test_mem.c
uc.c

I have forgott some corner cases in the snapshot restore methode.

Fix snapshot restore

---

.github/workflows/Crate-publishing.yml
.github/workflows/Nuget-publishing.yml
.github/workflows/PyPI-publishing.yml
.github/workflows/build-uc2.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/zigbuild.yml

First step to fix CI with:
- all warnings fixed
- "android cmake - gcc" fixed

Update github workflows

---

CMakeLists.txt

Fix the following warning during cmake configuration:
> CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
>
> Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.

Update cmake minimum required to version 3.5

---

qemu/include/tcg/tcg-apple-jit.h
qemu/target/ppc/excp_helper.c
uc.c

The gcc compiler version 13.2.0 complains about:
- unused variables in two macros (due to casting to void* instead of void)
- enum-int-mismatch in a method parameter
This small PR fixes these issues so the build log is warning and error free for gcc - under linux.

gcc compiler warning fixes

---

qemu/target/i386/translate.c
tests/unit/test_x86.c

References:
- https://gynvael.coldwind.pl/?id=268
- https://github.com/JonathanSalwan/Triton/issues/1131
This fixes the `bswap ax` detection as well as various other detections related to bad REX prefix handling. This bug is also still upstream in qemu, but they moved the code around quite a bit:
https://github.com/qemu/qemu/blob/ffeddb979400b1580ad28acbee09b6f971c3912d/target/i386/tcg/decode-new.c.inc#L2561-L2570
There are two fixes here:
- `bswap ax` now correctly sets `ax` to zero
- REX prefixes are correctly ignored when appropriate (they only apply when they are right next to the first byte of the instruction)

Fix emulator detection

---

qemu/target/riscv/cpu_bits.h
qemu/target/riscv/op_helper.c

The QEMU version currently used by Unicorn treats the `wfi` (wait for interrupt) instruction slightly incorrectly per the ratified wording in the RISC-V ISA specification. I believe this is because the QEMU implementation was originally based on an earlier revision (pre-ratification) and then the specification was subsequently refined.
This problem has been fixed in upstream QEMU in [`719f0f60`](https://github.com/qemu/qemu/commit/719f0f603c2289f438b8d6ef4358d9407b4c2905), and so this PR is proposing to backport that change to Unicorn without any modification except for the changed paths now being under the `qemu` directory.
The upstream commit gives the full details but the broad idea is that in U-Mode and S-Mode `wfi` should be treated as an invalid instruction exception in certain …

[QEMU backport] riscv: fix wfi exception behavior

---

qemu/target/riscv/translate.c

**Note:** I'm not sure if this is QEMU's bug or Unicorn's bug. I wasn't able to find a QEMU commit which had the line I removed here and so I suspect this was added in Unicorn, but I'm not sure which version of QEMU the current Unicorn was derived from and history shows this line being added as part of the Unicorn2 import mega-commit aaaea14214ed46ac60cf7ef5766374f660b05777.
If this _is_ QEMU's bug then it it appears to have been fixed upstream already but the relevant part of this code has been changed significantly to support dynamic registration of ISA extension decoders. QEMU code from just before [that redesign](https://github.com/qemu/qemu/commit/5e199b6bdc544658ecc9d614779b2cf3fe215ead) already lacks the line of code I removed, and I can't find any other earlier commit that …

riscv: Invalid 32-bit instruction should not decrement pc

---

bindings/python/sample_all.sh
bindings/python/unicorn/unicorn.py
bindings/python/unicorn/unicorn_py3/arch/__init__.py
bindings/python/unicorn/unicorn_py3/arch/arm.py
bindings/python/unicorn/unicorn_py3/arch/arm64.py
bindings/python/unicorn/unicorn_py3/arch/intel.py
bindings/python/unicorn/unicorn_py3/arch/types.py
bindings/python/unicorn/unicorn_py3/unicorn.py

Highlights:
- Miscellaneous re-arrangements following dual Python support
- Add initial support for batch operations

Misc. Python binding re-arrangements

---

qemu/accel/tcg/translate-all.c

Unicorn is already ignoring page locks, so we also don't need to manage the page collection and its tree objects. It helps us to avoid redundant object allocations and speed up the execution 3x faster for my case.

Ignore page_collection_lock

---

docs/FAQ.md
qemu/include/qemu/log.h
qemu/tcg/tcg.c

The qemu logs can be quite useful to understand, why the emulation does (not) work.
As an example, there is an open issue I had looked in (because I was curious) and did not find an easy way to
see the qemu logging - till I understood there arent anything compiled in.
I could write that script in cpp code and debug it - but I would like to have a "quick" way to figure out whats going on
with pyhton scripts too.
This PR revives the qemu_log for a "special" build - where you might want to try to find the bug or whats going on.
Example: Take the issue https://github.com/unicorn-engine/unicorn/issues/1971 and try to figure out whats going on with this PR and the enabled logs. You will see a message like:
It's more like to help developers to print useful log messages so we can figure out …

Revive qemu logs - and extend the FAQ

---

bindings/python/setup.py

It seems that the python bindings have great type hints, but due to the lack of a py.typed file, mypy doesn't use them.
This PR solves the issue.
I previously created #2000 from my master into this repo's master instead of dev.

Add py.typed to the Python binding package

---

qemu/target/i386/cpu.h
qemu/target/i386/unicorn.c

Highlights:
- Added read and write support for CR8, though changes to this reg have no effect currently
- Fixed a bug in which CR3 got updated whenever CR1 and CR2 were written
- Initial support for AVX512
- Added read and write support for XMM8-15 (all modes) and XMM16-31 (64-bit mode)
- Added read and write support for YMM8-15 (all modes) and YMM16-31 (64-bit mode)
- Added read and write support for ZMM0-31 (64-bit mode)
- Writes to XMMn were tested to be reflected in YMMn and ZMMn and vice versa

Add support for more Intel registers

---

qemu/target/sparc/unicorn.c

Fix a bug in which writes to I0 to I7 registers resulted in an error.

Fix SPARC I0-7 registers write

---

bindings/python/unicorn/unicorn_py3/arch/arm.py
bindings/python/unicorn/unicorn_py3/arch/arm64.py
bindings/python/unicorn/unicorn_py3/arch/intel.py
bindings/python/unicorn/unicorn_py3/arch/types.py
bindings/python/unicorn/unicorn_py3/unicorn.py
tests/regress/arm_memcpy_neon.py

Highlights:
- Redesign certain architecture-specific aspects to better leverage OOP
- Code de-duplication
- Easier to extend or support new architectures
- Now fully support `reg_write_batch` and `reg_read_batch` API
- Introduced coprocessor register accessors to AArch32 and AArch64, named `cpr_read` and `cpr_write`
- 1 ARM regression test fixed
- More comments, documentation and annotations

Support additional API on Python 3 bindings

---

bindings/python/unicorn/unicorn_py3/unicorn.py

Fix an assertion failure on encoding a ctl with no arguments.
Unbreaks `ctl_flush_tb()`.

Python: Fix assertion failure on ctl_flush_tb()

---

include/qemu.h
include/uc_priv.h
include/unicorn/unicorn.h
qemu/aarch64.h
qemu/arm.h
qemu/exec.c
qemu/include/exec/memory-internal.h
qemu/include/exec/memory.h
qemu/m68k.h
qemu/mips.h
qemu/mips64.h
qemu/mips64el.h
qemu/mipsel.h
qemu/ppc.h
qemu/ppc64.h
qemu/riscv32.h
qemu/riscv64.h
qemu/s390x.h
qemu/softmmu/memory.c
qemu/sparc.h
qemu/sparc64.h
qemu/tricore.h
qemu/unicorn_common.h
qemu/x86_64.h
symbols.sh
tests/benchmarks/cow/benchmark.c
uc.c

By using the memory snapshots with real examples we found some bottlenecks. Therefor I have implemented some optimizations.
We found that the flatview creation is quite expensive (around 1/4 of all runtime including emulation) when you have a lot of memory regions. By permanently creating new regions with CoW we have a lot of regions and rebuild for each cow the flatview again. I have added a update function does only change affected ranges.
Also we found that the `find_ram_offset_last` optimization doesn't work after a restore. To fix this the context now includes also the `ramblock_freed` bool.
This also includes two smaller optimizations: only clear the affected tlb on memory_cow and save the last `ramblock` of the `ram_list`
It's currently only a draft, because we need to do a few …

Optimize memory handling

---

bindings/python/unicorn/unicorn_py3/unicorn.py

Highlights:
- Add support for TLB fill hooks as requested in #2035 (_untested_)
Notes:
- Requires sanity testing
- Requires unit testing

Hook tlb fill

---

qemu/accel/tcg/cputlb.c
qemu/accel/tcg/translate-all.c
qemu/include/exec/exec-all.h
qemu/softmmu/cpus.c
tests/unit/test_x86.c
uc.c

This enables `notdirty_write` when used with snapshots. To do this the tlb is cleared on a snapshot and the priority of the mr is compared with the snapshot level.
It also fixes a bug when the mmu doesn't map 1:1. Before this the memory region was looked up with the vaddr, but memory regions are mapped at the paddr.
It's currently a draft because I also want to improve the `MEM_HOOK` check. As you already noticed in #2029 there are some hooks missing in the check. I would also include a range check for the hooks so only skip the optimization when there is a hook on this address.

Optimize Notdirty write

---

qemu/accel/tcg/cpu-exec.c
qemu/include/tcg/tcg.h
qemu/softmmu/unicorn_vtlb.c
qemu/tcg/aarch64/tcg-target.inc.c
uc.c

Submitted all together because creating separate pull requests would be annoying

Several bugfixes

---

bindings/rust/src/ffi.rs
bindings/rust/src/lib.rs
tests/rust-tests/main.rs

This is my proposed fix for adding reg_read_batch and reg_write_batch into the rust bindings. Issue #2059 
It's a bit janky as uc_reg_{read,write}_batch require the values to be passed as void** . Is there a better solution that I have overlooked?

Rust Bindings: reg_read_batch and reg_write_batch 

---

.github/workflows/build-wheels-publish.yml
bindings/python/README.md
bindings/python/pyproject.toml
bindings/python/setup.py
bindings/python/tests/test_arm64.py
bindings/python/tests/test_ctl.py
bindings/python/tests/test_network_auditing.py
bindings/python/tests/test_x86.py
bindings/python/unicorn/unicorn_py2.py
bindings/python/unicorn/unicorn_py3/unicorn.py

Python bindings:
- Fixed editable mode install and some more code cleanup in `setup.py`
- Added missing `license` field in `pyproject.toml` file
- Refreshed `README.md`
- Replaced f-string formatter in tests with `format` method in order to be py2-compatible
- Fixed typos
- PEP8 fixes
GitHub Action:
- Install Python2.7 and run tests for re-tagged wheels on native arch runners only

Python bindings: Fix editable install + Execute Python2.7 workflow tests

---

bindings/go/unicorn/hook.c
bindings/go/unicorn/hook.go
bindings/go/unicorn/hook.h
qemu/target/i386/misc_helper.c
qemu/target/i386/unicorn.c
tests/unit/test_x86.c

This patch allows the RDTSC and RDTSCP instructions to be hooked. The code is based on the CPUID hook implementation.
Fixes #2065

make i386 instructions RDTSC and RDTSCP hookable

---

Cargo.toml
bindings/rust/src/lib.rs

Found out the arch_aarch64 feature flag doesn't actually enable the arm64 module, and it bothered me a bit. Changed arch_aarch64 to depend on arch_arm of requiring manually enabling both arch_arm and arch_aarch64 at the same time.

improve aarch64 feature gate in rust bindings

---

qemu/include/tcg/tcg.h
qemu/tcg/aarch64/tcg-target.inc.c
qemu/tcg/i386/tcg-target.inc.c
qemu/tcg/ppc/tcg-target.inc.c

Directly jump into the slow path when there is any hookmem enabled. This fixes #1908.

qemu/tcg: fix UC_HOOK_MEM_READ on aarch64.

---

tests/unit/test_ctl.c
uc.c

`uc_ctl_set_page_size()` for arm64 is currently disallowed with `UC_ERR_ARG` despite being implemented and functional.
Allow for arm64, and add test.
Additionally tested with a rather involved arm64 unicorn project that makes extensive use of paging in pages on demand, no issues.

Allow uc_ctl_set_page_size() for arm64

---

qemu/configure

man clock_adjtime: #include <sys/timex.h>
for glibc, if _GNU_SOURCE is defined, <time.h> will include <sys/timex.h> but not for musl, so replce <time.h> to <sys/timex.h>
PS it seems clock_adjtime is used nowhere?

configure: update .h for clock_adjtime

---

qemu/target/mips/unicorn.c
tests/unit/test_mips.c

Fix for issue #2086 - this time based off the dev branch

Added start in mips16 mode support, and unit test for it - on dev branch

---

qemu/tcg/arm/tcg-target.inc.c
tests/unit/test_arm.c

Fix UC_HOOK_MEM on arm32

---

.github/workflows/build-uc2.yml
.github/workflows/build-wheels-publish.yml
bindings/python/unicorn/unicorn_py3/arch/arm64.py

Promote CpReg to a module-level class to address unnecessary performance reduction.
In a real-world use case tracing the emulation of real-world machine code, this change reduces time spent in CpReg namedtuple construction from 10% of overall time to below 1%, a ~ 10x speedup of the insn hook itself, or a ~ 10% overall speedup.  Measured using cProfile, python 3.13.

arm64 python: Avoid nested class in insn hook for 10x hook and 10% overall speedup

---

qemu/target/s390x/translate.c

Issue link: https://issues.oss-fuzz.com/issues/376723679
In this PR addresses a heap buffer overflow in the op_cksm function ensuring proper bounds checking and validation to prevent buffer overflows.

Fix heap buffer overflow in op_cksm function

---

.github/workflows/build-wheels-publish.yml
tests/regress/arm_movr12_hang.py
tests/regress/core_ctl.py
tests/regress/init.py
tests/regress/potential_memory_leak.py
tests/regress/translator_buffer.py

- Switched to the `ubuntu-24.04-arm` runner
- Bumped Windows runner to `windows-2022` and `Visual Studio 17 2022` GENERATORS
- Minor changes about checks in workflow jobs
- Fixed the pagefile job (even though should not be really needed)
- Refreshed the TO BE CHECKED regress tests to either update or remove the skip conditions
- Added a test to check if the created sdist archive is ok

Python bindings: Refreshing workflow + regress tests

---

qemu/target/arm/unicorn_arm.c
tests/unit/test_arm.c

Any attempt to write to UC_ARM_REG_C1_C0_2 ([The ARM Coprocessor Access Control Register](https://developer.arm.com/documentation/ddi0344/k/system-control-coprocessor/system-control-coprocessor-registers/c1--coprocessor-access-control-register)) fails with UC_ERR_ARG.
The specific switch case handling writes to this register was commented out since 2021, but by default, the error code was initialized to UC_REG_OK, so there was no error returned until #1835, where this was changed to be initialized to UC_REG_ERR_ARG. As a result, any write to UC_ARM_REG_C1_C0_2 returned an error.
In this PR, I've uncommented and properly implement the CPACR register write with appropriate size checking. I've also added a unit test to verify that writes no longer fail - before this PR, the test does indeed …

fix(arm): correct write to ARM coprocessor

---

qemu/target/ppc/mem_helper.c

This fixes the issue described in #2103 - compilation errors when building Unicorn Engine:
```
/build/unicorn-2.1.2/src/qemu/target/ppc/mem_helper.c: In function ‘helper_stq_le_parallel’:
/build/unicorn-2.1.2/src/qemu/target/ppc/mem_helper.c:423:12: error: ‘return’ with a value, in function returning void [-Wreturn-mismatch]
423 |     return 0;
|            ^
/build/unicorn-2.1.2/src/qemu/target/ppc/mem_helper.c: In function ‘helper_stq_be_parallel’:
/build/unicorn-2.1.2/src/qemu/target/ppc/mem_helper.c:439:12: error: ‘return’ with a value, in function returning void [-Wreturn-mismatch]
439 |     return 0;
|            ^
```
As pointed by @patryk4815
> Since GCC 14, the -Wreturn-mismatch warning has been promoted to an error by default (as mentioned …

Fix #2103: qemu/target/ppc/mem_helper.c remove redundant returns

---

.github/workflows/Crate-publishing.yml
.github/workflows/Nuget-publishing.yml
.github/workflows/build-uc2.yml

- Switched from windows-2019 to windows-2022
- Switched to ubuntu-24.04-arm image for Linux aarch64 jobs
- Fixed Linux x86 job. It was failing but not reported
- Switched from Visual Studio 16 2019 generators to Visual Studio 17 2022
- Un-commented Windows MINGW32 static and shared jobs
- Generic clean-up

GitHub Workflow: Updating jobs with new runners + fixes for Linux and windows x86 jobs

---

.github/workflows/Nuget-publishing.yml
.github/workflows/build-uc2.yml

- Remove a slash for aarch64 job that resulted to be a leftover from previous refactoring
- More cleanup

GitHub Workflow: Fix aarch64 build bug introduced with previous refactoring #2106

---

include/unicorn/mips.h
qemu/target/mips/cpu.c
tests/regress/mips64.py
uc.c

This PR allows MIPS64 to work - previously MIPS64 would crash immediately after starting the emulator - see #2109.
The current `uc_emu_start` code makes the assumptions that MIPS has a 32-bit program counter. Adding a check to see if it's 64-bit and writing the correct value to PC makes MIPS64 run.
https://github.com/unicorn-engine/unicorn/blob/8d52ece48bbb521060a5234ba1326d601be78315/uc.c#L1021-L1026

Support MIPS64 - write correct PC register width on uc_emu_start

---

.github/workflows/Nuget-publishing.yml
.github/workflows/build-uc2.yml
.github/workflows/build-wheels-publish.yml
bindings/python/pyproject.toml
bindings/python/unicorn/unicorn_py3/unicorn.py

Take over of https://github.com/unicorn-engine/unicorn/pull/2122
Closes: https://github.com/unicorn-engine/unicorn/issues/1829
Thanks to @Arusekk

Python bindings: Port pkg_resources to importlib_resources for python < 3.9

---

qemu/softmmu/memory.c
tests/unit/test_arm.c
tests/unit/test_arm64.c
tests/unit/test_riscv.c
tests/unit/test_x86.c
uc.c

Fixes use after free on snapshots restore.
Also some cleanup in the unit tests. Mostly forgot to call `uc_close`.
The sanitizer also finds some stack overflow in `test_x86_smc_add` and `test_x86_smc_mem_hook`. I'm currently don't understand the error.
In `test_context_snapshot` of `test_mem` there is an Memory leak which I'm currently debug.

Snapshot use after free

---

.github/workflows/build-uc2.yml

Added a job to run build & test into a musl-based linux distribution like Alpine. This should extend coverage and be sure things keep working fine
Related issues:
- https://github.com/unicorn-engine/unicorn/issues/1965
- https://github.com/unicorn-engine/unicorn/issues/2113

GitHub workflow: Add Alpine Linux job

---

bindings/zig/sample/sample_riscv_zig.zig

- Use full code length (instead of subtracting 1) when writing instructions.
- Uniformly zero-pad addresses in logs and print hexadecimal.
- Correct the instruction-hook callback in test_riscv2.

bindings/zig: Fix sample_riscv_zig partial writes and logging

---

qemu/accel/tcg/cputlb.c
qemu/include/exec/cpu-defs.h
qemu/include/exec/exec-all.h
tests/unit/test_arm.c

While experimenting with Unicorn to emulate an ARMv7 system that heavily utilizes LPAE, I noticed Unicorn would translate the virtual addresses properly. However, the address got truncated to 32-bits somewhere in the pipeline, which rendered my emulator inoperable.
I tracked down the problem to a couple of types in the `CPUTLBEntry` struct and surrounding functions. I've changed them from `target_ulong` to `hwaddr` (hopefully I didn't miss any).
This change seems to work for my setup, I haven't tried other architectures (such as x86 with PAE) but if my understanding of the code is correct, the change should be architecture-angostic.
When running `cargo test`, all tests seem to pass. However, I have not added new ones for this scenario.

Fix physical address truncation on 32-bit systems with addressing extensions

---

bindings/ruby/unicorn_gem/ext/unicorn.c

uc_query expects a size_t *, while we are passing uc_arch *. This has been working for a while as gcc just warned about this, however with latest gcc this changed into an error:
unicorn.c:122:34: error: passing argument 3 of ‘uc_query’ from incompatible pointer type [-Wincompatible-pointer-types]
206 |     uc_query(_uc, UC_QUERY_ARCH, &arch);
unicorn.h:689:60: note: expected ‘size_t *’ {aka ‘long unsigned int *’} but argument is of type ‘uc_arch *’
689 | uc_err uc_query(uc_engine *uc, uc_query_type type, size_t *result);
Fix this issue by querying the result into a size_t and later downcast the result into an uc_arch enum.

bindings: ruby: fix unexpected uc_query result pointer type

---

bindings/ruby/Makefile
bindings/ruby/unicorn_gem/lib/unicorn_engine/version.rb

It seems when bumping 2.1.2 and 2.1.3 some places have been forgotten. This actually results in a 2.1.1 gem file when building distro packages as a result.

bindings: ruby: fix version identifier to 2.1.3

---

bindings/rust/src/hook.rs
bindings/rust/src/lib.rs
bindings/rust/src/tests/arm.rs
bindings/rust/src/tests/arm64.rs
bindings/rust/src/tests/ppc.rs
bindings/rust/sys/build.rs
bindings/rust/sys/src/lib.rs

This is a follow-up to #2138
The Rust structs for ARM/ARM64 CP registers were named `RegisterARM(64)_CP` - this isn't conventional. Ideally, it should be `RegisterARM64CP`. Additionally, reading from the CP register was broken on ARM64, and neither ARM nor ARM64 had a write variant.
I've added a step in the `build.rs` to remove underscores in the register struct names sans the prefix/suffix, and have added write variants of the `coproc` functions. They also now take in a register as the argument, so users can manipulate which coprocessor register to read from. Lastly, I added some helper methods on these CP register structs to make it more ergonomic to construct them.

feat(rust): improve ARM CP register ergonomics

---

bindings/rust/src/tests/m68k.rs
qemu/m68k.h
qemu/target/m68k/cpu.h
qemu/target/m68k/helper.c
qemu/target/m68k/unicorn.c
symbols.sh
tests/unit/test_m68k.c

Closes #1733
The SR register in the `CPUM68KState` struct does not contain the value of the lower 5 flags. This causes incorrect reads, as noted in the aforementioned issue, where the value of the CCR bits is not present.
To compute the proper SR value, we must OR the CCR values with the SR register. In this PR, I've added a helper `cpu_m68k_get_sr` to compute the correct SR value when `uc_reg_read` is called with the M68K SR register. Now, one can use the SR register to check the carry, overflow, zero, negative, and extend flags.

fix(m68k): correct SR register read

---

bindings/python/unicorn/unicorn_py2.py
bindings/python/unicorn/unicorn_py3/unicorn.py

- Closes #2129
The unicorn wrappers handling exceptions during hook handling catch `Exception`s and not `BaseException`s, thereby skipping any `KeyboardInterrupt`s. It would be nice if keyboard interrupts stopped emulation.
Instead of catching `Exception` in the hook handling callbacks, we should catch `BaseException` as `KeyboardInterrupt` is derived from this ([docs](https://docs.python.org/3/library/exceptions.html#KeyboardInterrupt))
I've built the bindings locally, and ran the same script posted in the given issue above ^^ below is a screenshot of the output for me:

fix(python): catch `BaseException` in wrappers instead of `Exception`

---

bindings/rust/Cargo.toml
bindings/rust/src/lib.rs

In some situations, we hold a mutable reference to the user-defined data stored in `Unicorn` struct by `get_data_mut`, and we also need to call some mutable method like `reg_write` at the same time. However, currently Rust does not support inter-procedure field-granularity borrow checker (see [this blog](https://smallcultfollowing.com/babysteps/blog/2025/02/25/view-types-redux/) for more details), as a result, this makes it impossible to do this.
Since the `Unicorn` struct holds an `Rc` of `UnicornInner`, we can just cheaply clone the `Unicorn` to get rid of this.
In this PR, I use `perfect_derive` instead of simple `derive`, since Rust's derive will require the generic parameter `D` also implement `Clone`, which is unnecessary (See [this …

Make Unicorn struct clone-able

---

qemu/accel/tcg/tcg-runtime.c

Currently, once users have modified PC register via `uc_reg_write`, [this line](https://github.com/unicorn-engine/unicorn/blob/cad506442abf4cfeec2f7cbda5bd7a2f57bf9b78/uc.c#L711) will modify `uc->skip_sync_pc_on_exit` to be true. However, this value is never restored to false due to a typo in `qemu/accel/tcg/tcg-runtime.c`.
With this value being `true`, all followed memory hooks introduced in [this commit](https://github.com/unicorn-engine/unicorn/commit/b999f507b984930dec9e994e26f7c91c36a42a07) are never syncing PC, thus leading to wrong PC value got in memory hooks.
However, I'm sorry that I could not give a minimal reproducing example, since the testcase I used is far too large and complicated. Anyway, the typo is apparent and I think this patch should work.

Correctly restore skip_sync_pc_on_exit

---

bindings/dotnet/UnicornEngine/Unicorn.fs
bindings/dotnet/UnicornEngine/UnicornEngine.fsproj
bindings/dotnet/UnicornEngine/WinNativeImport.fs

Added CFG check on instance creation since unicorn doesn't support it and added "--standalone" flag to make it easier to work with the library.

Added CFG check and standalone flag for .NET binding

---

qemu/accel/tcg/translate-all.c

In x86 windows (NOT x64), the second argument of `AddVectoredExceptionHandler` is a function pointer that uses stdcall calling conv:
```c
// from winnt.h
#define NTAPI __stdcall
...
...
typedef LONG (NTAPI *PVECTORED_EXCEPTION_HANDLER)(
struct _EXCEPTION_POINTERS *ExceptionInfo
);
```
The trampoline `closure`, which is passed to `AddVectoredExceptionHandler`, is responsible to clean up args on stack. So the last instruction of `closure` should be `ret 4` instead of just `ret`, otherwise it would cause stack unbalance and you may get crash randomly.

fix incorrect ret of trampoline `closure` in `alloc_code_gen_buffer`

---

qemu/exec.c

ram_block_add() sets invalid_error when allocation fails. This is later checked for error handling.
fixes #2179

reset invalid_error before ram_block_add

---

bindings/rust/sys/build.rs

This enables `install` target in `build.rs`.

Enable install for rust bindings

---

.github/workflows/Crate-publishing.yml
.github/workflows/Nuget-publishing.yml
.github/workflows/build-uc2.yml

Remove the following warning in GitHub Actions with macOS runners:
> ninja 1.13.1 is already installed and up-to-date. To reinstall 1.13.1, run: brew reinstall ninja

Remove ninja installation from macos runners

---

.github/workflows/build-wheels-publish.yml
qemu/configure
qemu/include/tcg/tcg-apple-jit.h

The `read_sprr_perm` function now correctly works both on real Apple CPUs and in GitHub Actions virtualized environments by relying on `pthread_jit_write_protect_supported_np()`.
This ensures proper detection of JIT write protection status without depending on build-time msr register check.
As a result, building wheels for Apple ARM64 should now fully work fine.
Fixes:
- #2033
More context:
In `libsystem_pthread.dylib`, the function `_pthread_jit_write_protect_np` first checks whether JIT write protection is enabled by reading from a special memory location in the commpage: `0xfffffc10c`.
The same memory location is also checked by the `_pthread_jit_write_protect_supported_np` function.
In other words, whenever Apple code wants to access the `S3_6_c15_c1_5` system register using the `mrs` …

Fix `read_sprr_perm` for Apple real CPUs and GitHub Actions; enable Apple ARM64 wheel builds on PyPI. Fixes #2033.

---

CMakeLists.txt

Fix the following warning when using CMake 4.0:
```
CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
```

Bump cmake minimum required version to 3.10
