uc.c

uc.c: fix minor typo

---

tests/regress/Makefile
tests/regress/mem_double_unmap.c
uc.c

Fix for the first issue discussed in: #202

fix for use after free in case of double unmap

---

COMPILE.TXT

COMPILE.TXT: add note to configure Python for build

---

tests/regress/mips_kseg0_1.c

As requested, pull request for MIPS kseg0/1 range test case

Test for executing from  MIPS kseg0/kseg1 memory ranges

---

bindings/python/unicorn/unicorn.py

Related to https://github.com/unicorn-engine/unicorn/issues/225.
Hope this works in this way

Python bindings mem_protect and mem_unmap

---

tests/regress/Makefile
tests/regress/eflags_nosync.c

these commits should fix my previous ones.

X86 EFLAGS not synced properly.

---

include/uc_priv.h

l1_map should be an array of pointers, thus void **

Fix crash on 00 opcode.

---

qemu/tcg/aarch64/tcg-target.c
qemu/tcg/arm/tcg-target.c
qemu/tcg/ia64/tcg-target.c
qemu/tcg/mips/tcg-target.c
qemu/tcg/ppc/tcg-target.c
qemu/tcg/s390/tcg-target.c
qemu/tcg/sparc/tcg-target.c

related to #209
doesn't entirely fix non-x86, but this is the first step

improve multiarch support

---

.gitignore
tests/regress/Makefile
tests/regress/invalid_read_in_cpu_tb_exec_x86_64.c

Crash case: Invalid write of size 4 in cpu_tb_exec_x86_64 (issue #269)

---

qemu/target-i386/translate.c
qemu/tcg/tcg.c

Patch from here
http://lists.nongnu.org/archive/html/qemu-devel/2015-11/msg03848.html
Also fix another potential issue with constants from
https://github.com/qemu/qemu/commit/bbeb82395eaca0e3c38b433b2d2a5bad4a5fbd81#diff-9e0011b4d4a5890b309421630e6d86c3

Fix issue #269

---

bindings/go/unicorn/unicorn.go
bindings/python/unicorn/unicorn.py
include/uc_priv.h
include/unicorn/unicorn.h
qemu/include/exec/memory.h
qemu/memory.c
samples/sample_x86.c
tests/unit/test_mem_map_ptr.c
uc.c

add permissions to map_ptr api

---

tests/regress/Makefile
tests/regress/mips_delay_slot_code_hook.c

Tests that the code hook gets called for instructions in the branch delay slot for MIPS cpu.

Added MIPS delay slot code hook test.

---

.gitignore
tests/regress/Makefile
tests/regress/rw_hookstack.c

If address < 0x0030000 the hook isn't called.

Test for stack hooking.

---

tests/regress/hook_code_add_del.py

https://github.com/unicorn-engine/unicorn/issues/334
The code is a bit different than in the issue, but it should demonstrate the main problem just fine.

Add regress test for issue #334

---

qemu/aarch64.h
qemu/arm.h
qemu/header_gen.py
qemu/m68k.h
qemu/mips.h
qemu/mips64.h
qemu/mips64el.h
qemu/mipsel.h
qemu/sparc.h
qemu/sparc64.h
qemu/tcg/tcg.c
qemu/x86_64.h
tests/regress/tcg_liveness_analysis_bug_issue-287.py

Refer to https://github.com/unicorn-engine/unicorn/issues/287 for further info.

Fix possible wrong conditional branch in generated host code by fixing the tcg_liveness_analysis().

---

tests/unit/Makefile
tests/unit/test_tb_x86.c

for exercising proper flushing of the instruction translation cache.

Added unit test for TB flushing by x86_32 Self-modify of IMUL Gv, Ev, Ib instruction sequence

---

qemu/util/qemu-thread-posix.c

qemu-thread-posix: bail on mutex errors

---

bindings/java/samples/Sample_mips.java
bindings/java/samples/Sample_sparc.java
bindings/python/sample_sparc.py

uc_mode fixes for bindings
(samples didn't need any new fixes)

uc_mode fixes for bindings

---

tests/regress/Makefile
tests/regress/mem_fuzz.c
tests/unit/test_mem_map.c

Added a simple memory fuzzer and 2 resulting minized testcases that are currently failing.

added memory fuzzer and 2 resulting testcases

---

bindings/go/unicorn/hook.c
bindings/go/unicorn/hook.go
bindings/go/unicorn/hook.h
bindings/go/unicorn/unicorn.go
bindings/go/unicorn/unicorn_test.go
bindings/go/unicorn/x86.go
bindings/go/unicorn/x86_test.go

catch up on Go bindings

---

tests/regress/LICENSE

As discussed with @aquynh via email.

Add a license for regression tests

---

bindings/msvc/unicorn.def
bindings/msvc/unicorn_dynload.c
bindings/msvc/unicorn_dynload.h

Added uc_query(), uc_mem_map_ptr() and uc_mem_regions().
Updated uc_hook_add().

Updated MSVC bindings for new and changed functions.

---

bindings/ruby/unicorn_gem/ext/unicorn.h
tests/regress/x86_gdt.py

GDT regress test based on my GDT setting sample

GDT regress test

---

list.c
uc.c

hook management fixes

---

bindings/python/unicorn/unicorn.py

Addresses a couple of pep8 related changes improving the code quality.
As per #496.

code cleanup of python bindings

---

tests/regress/x86_64_eflags.py

This currently fails because of #499

Add test case for unicorn-engine/unicorn#499

---

make.sh

allow setting PREFIX in make.sh

---

tests/regress/translator_buffer.py

Testcase for the issue described here: https://github.com/unicorn-engine/unicorn/issues/508

test case for the dynmaic translator buffer issue

---

bindings/go/sample.go

Go bindings: fix HookAdd in sample

---

tests/regress/write_before_map.py

Regression test for https://github.com/unicorn-engine/unicorn/issues/532

added regression test write before map

---

qemu/target-arm/unicorn_arm.c

This is a fix for #538 
The vld.py regression test seems OK

Reading and writing NEON registers

---

tests/regress/arm_fp_vfp_disabled.py

Test case supplied on request. Relates to issue #571.
Please let me know if you need more information or would prefer the test case to be written in C rather than Python, or any other changes.
Thanks for looking into this,
Peter

Add arm_fp_vfp_disabled.py test.

---

tests/regress/arm_fp_vfp_disabled.py

Add Thumb-2 code to enable FP and VFP.

---

tests/unit/Makefile
tests/unit/test_hang.c

Added the test for AArch64 emulation hanging.

added ARM64 hang test

---

tests/regress/arm_fp_vfp_disabled.py

Fix incorrect end address passed to emu_start.

---

tests/regress/x86_fldt_fsqrt.py

Add regression test for fsqrt hang

---

bindings/python/unicorn/unicorn.py

I can confirm this works on Debian/Ubuntu and Fedora.

Fix issue #603

---

qemu/cpus.c

this makes precorn possible on glib < 2.46 :)

fix free() -> g_free()

---

docs/COMPILE-NIX.md
make.sh

Add linux32 option to make.sh, also update COMILE-NIX.md to reflex this change.

make.sh: add linux32 option

---

bindings/python/sample_x86.py
bindings/python/unicorn/unicorn.py
qemu/target-i386/unicorn.c
samples/sample_x86.c
tests/unit/test_x86.c

Support reading and writing to and from the x86 xmm registers. Only implements the python bindings.

support xmm registers

---

tests/regress/x86_self_modifying.py
tests/regress/x86_self_modifying.s

Document assembly instructions for x86_self_modifying

---

Makefile
bindings/python/Makefile
samples/Makefile

Remove BUILDDIR-specific code

---

bindings/python/sample_arm.py
samples/sample_arm.c

Added change to sample_arm as discussed in #638

Fixed ARM sample to properly run THUMB code #638

---

.appveyor.yml
.gitignore
.travis.yml
Makefile
bindings/Makefile
install-cmocka-linux.sh
samples/Makefile
tests/unit/Makefile
tests/unit/test_tb_x86.c

`osx` in Travis has `brew` available without `sudo`, easy to install `cmocka`
For `linux` and appveyor, I created a small script to download and compile `cmocka`.
Unit test `test_tb_x86_64_32_imul_Gv_Ev_Ib` now failing on all platforms
TODO: see if `clang` works in `cygwin` for builds, currently following up with cmocka
What about changing the `tests/unit` to pass and adding it to the build process? Maybe `bindings` too?

Run Unit Test in Travis builds

---

bindings/haskell/src/Unicorn.hs
bindings/haskell/src/Unicorn/CPU/Arm.chs
bindings/haskell/src/Unicorn/CPU/Arm64.chs
bindings/haskell/src/Unicorn/CPU/M68k.chs
bindings/haskell/src/Unicorn/CPU/Mips.chs
bindings/haskell/src/Unicorn/CPU/Sparc.chs
bindings/haskell/src/Unicorn/CPU/X86.chs
bindings/haskell/src/Unicorn/Hook.hs
bindings/haskell/src/Unicorn/Internal/Core.chs
bindings/haskell/src/Unicorn/Internal/Hook.chs
bindings/haskell/src/Unicorn/Internal/Unicorn.chs
bindings/haskell/src/Unicorn/Internal/Util.hs
bindings/haskell/src/cbits/unicorn_wrapper.c
bindings/haskell/src/include/unicorn_wrapper.h
bindings/haskell/unicorn.cabal

* Added support for `uc_alloc_*` functions (per issue #662)
* Fixed compiler error introduced by `UC_HOOK_MEM_READ_AFTER `
* Style fixes

Updates to Haskell bindings

---

bindings/haskell/samples/SampleX86.hs
bindings/haskell/src/Unicorn.hs
samples/sample_x86.c

Based off `test_i386_context_save` function in `bindings/python/sample_x86.py`.

Added uc_context_* sample

---

bindings/ruby/unicorn_gem/ext/unicorn.c

also fixup extra blank spaces at the end of lines.

fix signedness issue with reg read/write in ruby bindings

---

.travis.yml

cleanup travis by removing universal builds

---

qemu/target-arm/unicorn_arm.c

This PR adds the capability to set the `CPSR` register on the ARM architecture.

Allow the client to write to CPSR

---

include/unicorn/platform.h
qemu/include/qemu/compiler.h

Hopefully fixes snprintf() and isinf() compatibility defines.

Changed some MSVC compatibility defines based on MSVC version.

---

.appveyor.yml

add msvc build to msvc branch

---

bindings/ruby/Makefile
bindings/ruby/sample_x86.rb
bindings/ruby/unicorn_gem/ext/unicorn.c
bindings/ruby/unicorn_gem/ext/unicorn.h

I've updated the ruby bindings.

Updated ruby bindings

---

bindings/haskell/.gitignore
bindings/haskell/samples/SampleBatchReg.hs
bindings/haskell/samples/SampleX86.hs
bindings/haskell/src/Unicorn.hs
bindings/haskell/src/Unicorn/Internal/Hook.chs
bindings/haskell/src/Unicorn/Internal/Unicorn.chs
bindings/haskell/src/cbits/unicorn_wrapper.c
bindings/haskell/src/include/unicorn_wrapper.h

Adds Haskell bindings for the `uc_reg_write_batch` and `uc_reg_read_batch` functions

Haskell bindings update

---

bindings/python/sample_arm.py
qemu/target-arm/unicorn_arm.c

Support for reading writing ARM_REG_APSR. Only 4 msb. (no GE)

Add support for ARM application flags - APSR register

---

CREDITS.TXT

Refer to https://github.com/unicorn-engine/unicorn/pull/780#discussion_r105941840
Thanks

armeb: modify CREDITS.TXT.

---

samples/sample_all.sh

Added arm64eb sample to sample_all.sh script

Added arm64eb sample to sample_all.sh script

---

bindings/python/sample_arm64.py
bindings/python/sample_arm64eb.py
qemu/target-arm/translate-a64.c
samples/sample_arm64.c
samples/sample_arm64eb.c

swap fetched instruction code before disassemble it

arm64eb: arm64 big endian also using little endian instructions.

---

bindings/python/unicorn/unicorn.py
qemu/target-i386/unicorn.c

I've so far only modified the python bindings to work correctly with the YMM registers. The others will likely have to be modified as well.

Implemented read and write access to the YMM registers

---

include/unicorn/unicorn.h

Further clarifying the comments I PRed last week.

Update unicorn.h unmapped hook comments

---

bindings/ruby/unicorn_gem/ext/unicorn.c

typo fixed: contest_restore -> context_restore

---

qemu/tcg/arm/tcg-target.c

Allows Unicorn to compile on ARM.

Fix typo in ARM tcg-target.c

---

bindings/python/unicorn/unicorn.py

Sometimes, the finalizer for an `UcRef` runs so late that the members of the
module have already been set to `None`. We need to make sure that we don't
depend on anything in the module, or we risk getting a Exception when we try
to access the `release_handle` method of `None` (`Uc`).

python: Fix exception in finalizer at exit

---

.travis.yml

use new travis osx image and brew

---

Makefile
qemu/util/oslib-posix.c

```
/Code/unicorn/samples> ./sample_all.sh 
==========================
Emulate i386 code
>>> Tracing basic block at 0x1000000, block size = 0x6
>>> Tracing instruction at 0x1000000, instruction size = 0x1
>>> --- EFLAGS is 0x0
>>> Tracing instruction at 0x1000001, instruction size = 0x1
>>> --- EFLAGS is 0x4
>>> Tracing instruction at 0x1000002, instruction size = 0x4
>>> --- EFLAGS is 0x10
>>> Emulation done. Below is the CPU context
>>> ECX = 0x1235
>>> EDX = 0x788f
>>> XMM0 = 0x00112233445566778899aabbccddeeff
>>> Read 4 bytes from [0x1000000] = 0xf664a41
===================================
Emulate i386 code - use uc_mem_map_ptr()
>>> Tracing basic block at 0x1000000, block size = 0x6
>>> Tracing instruction at 0x1000000, instruction size = 0x1
>>> --- EFLAGS is 0x0
>>> Tracing …
```

Haiku support patches

---

CREDITS.TXT

Adding Philippe Antoine to CREDITS

---

bindings/README

Fixes https://github.com/D-Programming-Deimos/unicorn/issues/1

bindings/README: Add D bindings

---

qemu/target-sparc/translate.c

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10335
Testcase is "fa7c01ff"

Sparc increase ttl number

---

qemu/target-m68k/helper.c
qemu/target-m68k/translate.c

Raises exception instead
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10331

Prevents abort with m68K

---

qemu/target-m68k/translate.c

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10438

Removes accessible assert

---

qemu/target-arm/translate.c

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10420
@aquynh :
Should there be a more global rebase on latest qemu code ?
And the other way around, should we push our changes to qemu ?

Uses latest qemu arm thumb load store stuff

---

bindings/README

Closes https://github.com/dargueta/unicorn-lua/issues/1

Add Lua binding to README

---

include/unicorn/x86.h
qemu/target-i386/unicorn.c

Added support for reading from and writing to the MXCSR register.
Added the correct way to write to FPUCW
Fixes #1058
Will add tests in the future.

Added MXCSR register, fixed writing to FPUCW.

---

.travis.yml

trusty is sunsetting support in April 2019

Add xenial support

---

bindings/go/unicorn/unicorn.go
bindings/go/unicorn/x86.go

Added X86MsrWrite and X86MsrRead to the golang bindings.

added x86Msr Functions

---

uc.c

I prevent the duplication of data when splitting memory regions by checking the ram block flag associated to the MemoryRegion struct.
I actually don't like the fact that I need to loop on the uc->ram_list.blocks to find the required block, but I was not able to find any other way to do this.

Don't duplicate a uc_mem_map_ptr'd memory region when splitting it (#1028)

---

make.sh

remove broken iOS builds

---

.travis.yml

fix broken build

---

README.md
bindings/README

Add ref to https://github.com/guillep/pharo-unicorn
Tx! :)

Add pharo-unicorn to binding list

---

.travis.yml

remove brew check with gcc and don't use `compiler` option in homebrew test, it isn't respected

brew ignores CC variable

---

.appveyor.yml

@aquynh this pushes all of the windows `dll`s into build artifacts. Is there anything else you're thinking of?

test appveyor artifacts

---

include/unicorn/platform.h
qemu/glib_compat.c
qemu/include/qemu/compiler.h
qemu/target-arm/unicorn_arm.c
qemu/target-i386/translate.c
qemu/target-m68k/helper.c
qemu/target-m68k/translate.c
qemu/target-mips/helper.c

Tested on Windows with VS2019.
Tested on Linux with gcc-7.4.0.
Includes the changes of "include/unicorn/platform.h" and "qemu/include/qemu/compiler.h" which are on the cmake branch.

Remove warnings

---

bindings/python/setup.py

https://github.com/unicorn-engine/unicorn/issues/1143 for more information.

Fixes #1143

---

CREDITS.TXT
qemu/configure
qemu/scripts/ordereddict.py
qemu/scripts/qapi-types.py
qemu/scripts/qapi-visit.py
qemu/scripts/qapi.py

compatible with python2 and python3.
tested on Ubuntu-18.04-amd64 with pyhton-2.7.15+ and python-3.6.8.

compatible with python2 and python3

---

Makefile

move default python2 search to lower priority

Update Makefile: move default python2 search to lower priority

---

tests/fuzz/Makefile
tests/regress/Makefile
tests/unit/Makefile

Tests, fixes on third platform.

---

qemu/fpu/softfloat.c
qemu/target-arm/translate-a64.c
qemu/target-arm/translate.c
qemu/target-i386/translate.c
qemu/target-mips/helper.c
qemu/target-mips/translate.c
qemu/target-sparc/translate.c
qemu/translate-all.c

fix some oss-fuzz bugs: 10419, 10427, 10421, 10422, 10425, 10426, 10460.

fix some oss-fuzz bugs

---

qemu/target-i386/unicorn.c

Fixes LM flag for CPUID extended feature mask

---

qemu/target-mips/translate.c

extend all imm from uint16_t to uint32_t in decode_opc().

fix mips bugs

---

qemu/cpu-exec.c
qemu/fpu/softfloat.c
qemu/target-arm/internals.h
qemu/target-arm/neon_helper.c
qemu/target-arm/translate.c
qemu/target-i386/ops_sse.h
qemu/target-mips/translate.c
qemu/target-sparc/helper.c
qemu/tcg/optimize.c
qemu/tcg/tcg.c
qemu/translate-all.c

fix some oss-fuzz bug: 20079, 20209, 20210, 20262.

fix some oss-fuzz

---

README.md

Follow-on to https://github.com/unicorn-engine/unicorn/pull/1050 -- missed a spot

Add Lua binding to main README

---

CMakeLists.txt
Makefile

fix finding python path which only has python3.

fix finding python path which only has python3

---

.github/workflows/cifuzz.yml
.travis.yml
qemu/target-arm/unicorn_arm.c
tests/fuzz/Makefile
tests/fuzz/dlcorpus.sh
tests/fuzz/onedir.c

This PR does multiple things :
- adds CIFuzz (GitHub workflow to test Pull Requests with fuzzers)
- Fixes one memory leak in watchpoint for ARM. This leak should be fixed in other architectures
- Adds builds to Travis, with fuzz targets and sanitizers, and run the fuzz targets on the public corpus (to be tested)

Oss-fuzz ideal integration

---

qemu/target-arm/neon_helper.c
qemu/unicorn_common.h

Leak on breakpoints
Undefined shift in ARM

Removes some bugs found by oss-fuzz

---

qemu/exec.c

fix error handling of mmap() calls

---

.github/workflows/python-publish.yml
.travis.yml

Adding test pypi step to check if uploads are in order then only publish to pypi.org
**Required**
secret for test pypi token named "**testpypi_pass**" to be created.

PyPI test check

---

qemu/target-i386/unicorn.c

Fix for #1320.
I'm not sure whether it's the right place to fix. Any instruction or advice is highly welcome.

Fix IP value for UC_MODE_16

---

qemu/aarch64.h
qemu/aarch64eb.h
qemu/arm.h
qemu/armeb.h
qemu/header_gen.py
qemu/target-arm/cpu.c
qemu/target-arm/cpu64.c

fix aarch64 cpu init error

---

qemu/target-i386/ops_sse.h

Merge from qemu commit 1e8a98b53867f61da9ca09f411288e2085d323c4.
https://github.com/qemu/qemu/commit/1e8a98b53867f61da9ca09f411288e2085d323c4

Return 'indefinite integer value' for invalid SSE fp->int conversions

---

bindings/java/Makefile.build

FIX java binding compilation #1339

---

bindings/README

Add Javascript Unicorn.js to binding list

Add Javascript to binding list

---

samples/sample_arm.c

Add the sample from #853 to sample-arm.c.

Add arm ite blocks samples from #853

---

.github/workflows/PyPI-publishing.yml
bindings/python/build_wheel.sh

Updates:-
1. Updated to dockcross manylinux2014
2. windows build with cmake/ninja

PyPI publishing

---

tests/unit/test_x86.c

This adds a unit test to reproduce #1495.

Add test case for #1495

---

qemu/target/m68k/unicorn.c

Added SR to M68K reg_read and reg_write

---

qemu/accel/tcg/cpu-exec.c
tests/unit/test_ppc.c

Refer: 67e2386da6eb153e43a2f8bce36552ece33a3821

Fix pc after ppc sc inst

---

bindings/vb6/Apache_2.0_License.txt
bindings/vb6/Form1.frm
bindings/vb6/Project1.vbp
bindings/vb6/README.txt
bindings/vb6/main.cpp
bindings/vb6/ucIntel32.cls
bindings/vb6/uc_def.bas

hopefully this is correct or I will just attach the files

vb6 bindings: clarify Apache license as v2.0

---

qemu/include/qemu/host-utils.h

[#1573](https://github.com/unicorn-engine/unicorn/pull/1573)

Fix clang-cl compile with CONFIG_INT128 in qemu

---

.gitignore
bindings/python/unicorn/unicorn.py
bindings/ruby/Makefile
bindings/ruby/unicorn_gem/lib/unicorn_engine/version.rb
bindings/rust/README.md

The next release version will be `2.0.0`, so I change them to it.

Fix outdated version

---

tests/unit/test_ctl.c

Apple Silicon does not allow RWX pages so the mmap call was returning -1. This changes the test to map as RW and then mprotect it back and forth between RX/RW as needed.

Fix test_uc_hook_cached_uaf for MacOS M1 (aarch64).

---

bindings/python/unicorn/unicorn.py

Use libunicorn.so.2 as fallback path

---

.github/workflows/stale.yml
ChangeLog
glib_compat/grand.c
tests/unit/acutest.h

* Haiku is fully posix, so can be lumped together with most unix cases

build: Fixes for Haiku

---

include/unicorn/unicorn.h
uc.c

Some clean-up to the vtlb merge. Sorry that I have missed this before the merge.

Some clean-up for the vtlb merge

---

qemu/softmmu/unicorn_vtlb.c
tests/unit/test_ctl.c

vtlb only cache access permisions required for the operation

---

bindings/rust/src/ffi.rs

Move the unsafe for functions that dereference a pointer that is passed as unsafe to function level. For an explanation why this was bad see here: https://rust-lang.github.io/rust-clippy/master/index.html#/not_unsafe_ptr_arg_deref

fix: Make functions that deref ptr unsafe

---

bindings/rust/src/lib.rs
bindings/rust/src/unicorn_const.rs

Title is self-explanatory.
Please first merge #1871

Add uc_ctl_context_mode to rust bindings

---

.github/workflows/PyPI-publishing.yml
bindings/python/build_wheel.sh
bindings/python/setup.py

 Remove using of distutils

---

tests/regress/arm64_reg_rw_w0_w30.py
tests/regress/core_ctl.py
tests/regress/high_mem.py
tests/regress/hook_readonly_write_local.py
tests/regress/memmap_segfault.py
tests/regress/sparc_reg.py

Highlights:
- Minor fixes
- Uncomment known failures to encourage their fixes

Minor Python regress fixes

---

.github/workflows/build-uc2.yml
.github/workflows/build-wheels-publish.yml

- Fix upload-artifact actions in build wheel workflow
- Manually trigger workflow jobs to produce either Debug or Release builds

Feat: Option to manually specify the build type in the workflow

---

bindings/python/unicorn/unicorn_py3/unicorn.py

Have TLB fill hook return a `bool` as it should, following [this](https://github.com/unicorn-engine/unicorn/pull/2037/files#r1810834858) comment.

Fix TLB fill hook

---

bindings/rust/sys/build.rs

If a C source file is edited, and then subsequently a Rust build/test run is trigger, the code is not recompiled. This is because rustc doesn't know to rerun the build script when these C files change.
In this PR, I've added support for emitting the rust instruction to rerun the build script when any C files change, instead of having to have to trigger it manually.

fix(rust): watch all source and header files

---

bindings/rust/src/lib.rs
bindings/rust/src/tests/ctl.rs
bindings/rust/src/tests/m68k.rs

This makes it easier to do some FFI stuff. And it is consistent with `new` and `new_with_data`.

Add from_handle_with_data method

---

bindings/rust/src/hook.rs
bindings/rust/src/lib.rs

I've currently completed a rough version of unicornafl to add ability to cache TBs across forking (that code change is relatively large and thus requires further cleanup in a few days). This change is necessary for that feature.

Add edge generated callback

---

include/unicorn/sparc.h
qemu/accel/tcg/cpu-exec.c
qemu/target/sparc/unicorn.c

Port patches from https://pqsrc.cr.yp.to/saferewrite-20250505/unicorn-patch

Patch from Saferewrite

---

bindings/rust/src/lib.rs
include/unicorn/unicorn.h
uc.c

Minor fixes for vmem apis
